# Generated by Django 3.2.8 on 2024-11-28 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='notice',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
