# Generated by Django 3.2.8 on 2024-07-03 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0002_alter_electricitybill_previous_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.DateField(default=django.utils.timezone.now, help_text='The month for this bill')),
                ('total_amount_bill', models.DecimalField(decimal_places=2, help_text='Total amount of the bill', max_digits=10)),
                ('pick_unit', models.DecimalField(decimal_places=2, help_text='Pick unit consumption', max_digits=10)),
                ('off_pick_unit', models.DecimalField(decimal_places=2, help_text='Off-pick unit consumption', max_digits=10)),
                ('total_unit', models.DecimalField(decimal_places=2, editable=False, help_text='Total unit consumption', max_digits=10)),
                ('per_unit_price', models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit', max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='bill_name',
        ),
        migrations.DeleteModel(
            name='BillName',
        ),
        migrations.DeleteModel(
            name='ElectricityBill',
        ),
    ]
