# Generated by Django 3.2.8 on 2024-07-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0004_auto_20240703_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Renter's name", max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Renter',
                'verbose_name_plural': 'Renters',
            },
        ),
        migrations.AlterModelOptions(
            name='motherbill',
            options={'verbose_name': 'Mother Meter', 'verbose_name_plural': 'Mother Meters'},
        ),
        migrations.CreateModel(
            name='RenterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_meter_reading', models.DecimalField(decimal_places=2, editable=False, help_text='Previous meter reading', max_digits=10)),
                ('current_meter_reading', models.DecimalField(decimal_places=2, help_text='Current meter reading', max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='meters/')),
                ('total_unit', models.DecimalField(decimal_places=2, editable=False, help_text='Total unit consumption for the renter', max_digits=10)),
                ('per_unit_price', models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Total price for the renter', max_digits=10)),
                ('mother_bill', models.ForeignKey(help_text='Select the MotherBill', on_delete=django.db.models.deletion.CASCADE, to='haq_tower.motherbill')),
                ('renter', models.ForeignKey(help_text='Select the Renter', on_delete=django.db.models.deletion.CASCADE, to='haq_tower.renter')),
            ],
            options={
                'verbose_name': 'Renter Meter',
                'verbose_name_plural': 'Renter Meters',
            },
        ),
    ]
