# Generated by Django 3.2.8 on 2024-07-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0005_auto_20240704_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherbill',
            old_name='current_month',
            new_name='date',
        ),
    ]
