# Generated by Django 3.2.8 on 2024-07-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0006_rename_current_month_motherbill_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherbill',
            options={'verbose_name': 'Mother Bill', 'verbose_name_plural': 'Mother Bills'},
        ),
    ]
