# Generated by Django 3.2.8 on 2024-07-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0007_alter_motherbill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherbill',
            options={'verbose_name': 'Mother Meter', 'verbose_name_plural': 'Mother Meters'},
        ),
    ]
