# Generated by Django 3.2.8 on 2024-07-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0008_alter_motherbill_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentermeter',
            old_name='current_meter_reading',
            new_name='total_current_meter_reading',
        ),
        migrations.RemoveField(
            model_name='rentermeter',
            name='attachment',
        ),
        migrations.CreateModel(
            name='CurrentMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_meter_reading', models.DecimalField(decimal_places=2, help_text='Current meter reading', max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='meters/')),
                ('renter_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_readings', to='haq_tower.rentermeter')),
            ],
        ),
    ]
