# Generated by Django 3.2.8 on 2024-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0009_auto_20240710_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='logo',
            field=models.ImageField(blank=True, help_text="Renter's logo", null=True, upload_to='renter_logos/'),
        ),
    ]
