# Generated by Django 3.2.8 on 2024-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0010_renter_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherbill',
            name='off_pick_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Off-pick unit consumption', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='motherbill',
            name='pick_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pick unit consumption', max_digits=10, null=True),
        ),
    ]
