# Generated by Django 3.2.8 on 2025-01-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0011_auto_20240729_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmeterreading',
            name='current_meter_reading',
            field=models.DecimalField(decimal_places=2, help_text='Current meter reading', max_digits=15),
        ),
    ]
