# Generated by Django 3.2.8 on 2025-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0012_alter_currentmeterreading_current_meter_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherbill',
            name='off_pick_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Off-pick unit consumption', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='motherbill',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='motherbill',
            name='pick_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pick unit consumption', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='motherbill',
            name='total_amount_bill',
            field=models.DecimalField(decimal_places=2, help_text='Total amount of the bill', max_digits=15),
        ),
        migrations.AlterField(
            model_name='motherbill',
            name='total_unit',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total unit consumption', max_digits=15),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='previous_meter_reading',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Previous meter reading', max_digits=15),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='total_current_meter_reading',
            field=models.DecimalField(decimal_places=2, help_text='Current meter reading', max_digits=15),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total price for the renter', max_digits=15),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='total_unit',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total unit consumption for the renter', max_digits=15),
        ),
    ]
