# Generated by Django 5.0.6 on 2025-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0013_auto_20250123_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentermeter',
            name='total_unit',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total unit consumption for the renter', max_digits=15, null=True),
        ),
    ]
