# Generated by Django 5.0.6 on 2025-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0014_alter_rentermeter_total_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentermeter',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='total_current_meter_reading',
            field=models.DecimalField(decimal_places=2, help_text='Current meter reading', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rentermeter',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total price for the renter', max_digits=15, null=True),
        ),
    ]
