# Generated by Django 5.0.6 on 2025-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0015_alter_rentermeter_per_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentermeter',
            name='previous_meter_reading',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Previous meter reading', max_digits=15, null=True),
        ),
    ]
