# Generated by Django 5.0.6 on 2025-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0016_alter_rentermeter_previous_meter_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentermeter',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=4, editable=False, help_text='Price per unit', max_digits=15, null=True),
        ),
    ]
