# Generated by Django 5.0.6 on 2025-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq_tower', '0017_alter_rentermeter_per_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherbill',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=4, editable=False, help_text='Price per unit', max_digits=15),
        ),
    ]
