# Generated by Django 3.2.8 on 2025-02-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_management', '0003_alter_inventoryunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'permissions': (('can_change_inventory_status', 'Can Change Inventory status'),), 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='updated_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_management_inventorytransaction_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
