# Generated by Django 3.2.8 on 2025-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_auto_20250530_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
