# Generated by Django 3.2.8 on 2025-08-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_inventoryitem_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
