# Generated by Django 3.2.8 on 2025-08-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_auto_20250828_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='head',
        ),
    ]
