# Generated by Django 3.2.8 on 2025-09-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_remove_inventoryitem_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory Summary',
                'verbose_name_plural': 'Inventory Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory_management.inventorytransaction',),
        ),
    ]
