# Generated by Django 3.2.8 on 2025-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_inventorysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='available_item',
            field=models.PositiveIntegerField(default=0, help_text='Before this transaction'),
        ),
    ]
