# Generated by Django 3.2.4 on 2021-06-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=155)),
                ('slug', models.CharField(max_length=255)),
                ('job_context', models.TextField(max_length=500)),
                ('job_description', models.TextField(null=True)),
                ('job_responsibility', models.TextField(null=True)),
                ('educational_requirement', models.TextField(null=True)),
                ('additional_requirement', models.TextField()),
                ('compensation', models.TextField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_board_job_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSummery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_deadline', models.DateField()),
                ('experience', models.IntegerField(max_length=11)),
                ('job_type', models.CharField(max_length=22)),
                ('vacancy', models.IntegerField(max_length=11)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_board_jobsummery_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_board.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
