# Generated by Django 3.1.7 on 2021-03-09 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('experience', models.CharField(max_length=255)),
                ('last_date', models.DateField()),
                ('position', models.IntegerField(max_length=11)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('email', 'Email'), ('url', 'URL')], max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.job')),
            ],
            options={
                'db_table': 'job_forms',
            },
        ),
    ]
