# Generated by Django 3.1.7 on 2021-03-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20210311_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('number', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, upload_to='logo/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.job')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
