# Generated by Django 3.2.4 on 2021-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20210626_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='compensation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
