# Generated by Django 3.2.4 on 2021-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_alter_job_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsummery',
            name='experience',
            field=models.IntegerField(help_text='Experience in year', max_length=11),
        ),
    ]
