# Generated by Django 3.1.7 on 2021-03-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
