# Generated by Django 3.2.4 on 2021-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_auto_20210626_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='candidate/avatar/')),
                ('cv', models.FileField(upload_to='hr/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='jobsummery',
            name='experience',
            field=models.IntegerField(help_text='Experience in year'),
        ),
        migrations.AlterField(
            model_name='jobsummery',
            name='vacancy',
            field=models.IntegerField(),
        ),
    ]
