# Generated by Django 3.1.7 on 2021-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_auto_20210316_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
