# Generated by Django 3.1.7 on 2021-03-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_auto_20210316_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapply',
            options={},
        ),
        migrations.RenameField(
            model_name='jobapply',
            old_name='email',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='number',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='text',
        ),
        migrations.AlterModelTable(
            name='jobapply',
            table='job_applys',
        ),
    ]
