# Generated by Django 3.2.4 on 2021-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_auto_20210626_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', max_length=10),
        ),
    ]
