# Generated by Django 3.2.4 on 2021-06-27 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0007_auto_20210627_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CandidateJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mcq_exam_score', models.FloatField(default=0)),
                ('written_exam_score', models.FloatField(default=0)),
                ('viva_exam_score', models.FloatField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='job_board.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
