# Generated by Django 3.1.7 on 2021-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_auto_20210316_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
