# Generated by Django 3.2.8 on 2024-11-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0069_jobpreferencerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': (('can_see_candidate_expected_salary', 'Can See Candidate Expected Salary'),)},
        ),
    ]
