# Generated by Django 3.2.8 on 2025-01-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0070_alter_candidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('waiting', 'Waiting List'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('hired', 'Hired')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='schedule_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
