# Generated by Django 3.2.8 on 2025-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0071_auto_20250102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('none', 'None'), ('waiting', 'Waiting List'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('hired', 'Hired')], default='none', max_length=20),
        ),
    ]
