# Generated by Django 3.2.8 on 2025-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0072_alter_candidate_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('none', 'None'), ('waiting', 'Waiting List'), ('rejected', 'Rejected'), ('trial', 'Trial'), ('offered', 'Offered'), ('hired', 'Hired')], default='none', max_length=20),
        ),
    ]
