# Generated by Django 3.2.8 on 2025-01-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0074_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplicationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('application_count', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.job')),
            ],
        ),
    ]
