# Generated by Django 3.2.8 on 2025-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0076_alter_candidate_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplicationsummary',
            options={'verbose_name_plural': 'Candidate Application Summaries'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('none', 'None'), ('rescheduled', 'Rescheduled'), ('waiting', 'Waiting List'), ('rejected', 'Rejected'), ('trial', 'Trial'), ('offered', 'Offered'), ('hired', 'Hired')], default='none', max_length=20),
        ),
    ]
