# Generated by Django 3.2.8 on 2025-01-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0077_auto_20250108_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplicationsummary',
            options={'verbose_name': 'Re-opportunity to Candidate', 'verbose_name_plural': 'Re-opportunity to Candidates'},
        ),
    ]
