# Generated by Django 3.2.8 on 2025-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0079_alter_candidate_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('none', 'None'), ('scheduled', 'Scheduled'), ('attended', 'Attended'), ('rescheduled', 'Rescheduled'), ('waiting', 'Waiting List'), ('rejected', 'Rejected'), ('trial', 'Trial'), ('offered', 'Offered'), ('hired', 'Hired')], default='none', max_length=20),
        ),
    ]
