# Generated by Django 3.2.8 on 2024-06-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
