# Generated by Django 3.2.8 on 2024-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
    ]
