# Generated by Django 3.2.8 on 2024-06-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0160_client_is_hour_breakdown'),
        ('website', '0044_auto_20240613_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='clients',
            field=models.ManyToManyField(blank=True, to='project_management.Client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='industry',
            field=models.ManyToManyField(blank=True, to='website.Industry'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_process',
            field=models.ManyToManyField(blank=True, to='website.ServiceProcess'),
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_servicecontent_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
