# Generated by Django 3.2.8 on 2024-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20240628_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
