# Generated by Django 3.2.8 on 2024-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_service_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
