# Generated by Django 3.2.8 on 2024-07-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_hireresource_hireresourcecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireresource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
