# Generated by Django 3.2.8 on 2024-07-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_alter_hireresource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireresourcecontent',
            name='awards',
            field=models.ManyToManyField(to='website.Award'),
        ),
        migrations.AlterField(
            model_name='hireresourcecontent',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_contents', to='website.hireresource', verbose_name='Hire Resource'),
        ),
    ]
