# Generated by Django 3.2.8 on 2024-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20240704_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
