# Generated by Django 3.2.8 on 2024-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20240704_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireresource',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
