# Generated by Django 3.2.8 on 2024-07-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20240704_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireresource',
            name='title',
            field=models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255),
        ),
        migrations.AlterField(
            model_name='hireresourcecontent',
            name='title',
            field=models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_resource_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='website.hireresourcecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
