# Generated by Django 3.2.8 on 2024-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20240704_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
