# Generated by Django 3.2.8 on 2024-07-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20240704_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireResourceStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HireResourceStatisticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('junior', models.CharField(help_text='Statistic Value Respectively for Junior Developer', max_length=100, verbose_name='Junior Developer')),
                ('mid', models.CharField(help_text='Statistic Value Respectively for Mid Level Developer', max_length=100, verbose_name='Mid Level Developer')),
                ('senior', models.CharField(help_text='Statistic Value Respectively for Senior Developer', max_length=100, verbose_name='Senior Developer')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_statistic_contents', to='website.hireresourcestatistic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='statistic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_contents', to='website.hireresourcestatistic'),
        ),
    ]
