# Generated by Django 3.2.8 on 2024-07-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0166_alter_dailyprojectupdategroupbyclient_options'),
        ('website', '0057_auto_20240704_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireResourceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('hire_resource_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='website.hireresourcecontent')),
                ('technologies', models.ManyToManyField(to='project_management.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
