# Generated by Django 3.2.8 on 2024-07-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_hireresourcetechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireResourceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HireResourceFeatureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feature_image')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_feature_contents', to='website.hireresourcefeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_contents', to='website.hireresourcefeature'),
        ),
    ]
