# Generated by Django 3.2.8 on 2024-07-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20240704_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiringProcessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='hiring_process_icon')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_process_contents', to='website.hiringprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='hire_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_contents', to='website.hiringprocess'),
        ),
    ]
