# Generated by Django 3.2.8 on 2024-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_auto_20240704_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringprocesscontent',
            name='process',
        ),
        migrations.AddField(
            model_name='hiringprocess',
            name='content',
            field=models.ManyToManyField(blank=True, to='website.HiringProcessContent'),
        ),
    ]
