# Generated by Django 3.2.8 on 2024-07-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_auto_20240704_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireresourcestatisticcontent',
            name='statistic',
        ),
        migrations.AddField(
            model_name='hireresourcestatistic',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='website.hireresourcestatisticcontent'),
        ),
    ]
