# Generated by Django 3.2.8 on 2024-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_auto_20240704_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireresourcestatistic',
            name='content',
        ),
        migrations.AddField(
            model_name='hireresourcestatistic',
            name='content',
            field=models.ManyToManyField(related_name='statistics', to='website.HireResourceStatisticContent'),
        ),
    ]
