# Generated by Django 3.2.8 on 2024-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_auto_20240704_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireservicecontent',
            name='service',
        ),
        migrations.AddField(
            model_name='hireservice',
            name='content',
            field=models.ManyToManyField(blank=True, to='website.HireServiceContent'),
        ),
    ]
