# Generated by Django 3.2.8 on 2024-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20240704_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireresourcefeaturecontent',
            name='feature',
        ),
        migrations.AddField(
            model_name='hireresourcefeature',
            name='content',
            field=models.ManyToManyField(blank=True, to='website.HireResourceFeatureContent'),
        ),
    ]
