# Generated by Django 3.2.8 on 2024-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_auto_20240704_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireresourcecontent',
            name='image',
            field=models.ImageField(null=True, upload_to='hire_resource'),
        ),
    ]
