# Generated by Django 3.2.8 on 2024-07-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_hireresourcecontent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireresourcefeature',
            name='content',
        ),
        migrations.RemoveField(
            model_name='hireresourcefeaturecontent',
            name='image',
        ),
        migrations.AddField(
            model_name='hireresourcefeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_image'),
        ),
        migrations.AddField(
            model_name='hireresourcefeaturecontent',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_contents', to='website.hireresourcefeature'),
        ),
    ]
