# Generated by Django 3.2.8 on 2024-07-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_auto_20240705_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='HirePageStaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='hire_page')),
                ('hire_resource_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_page_static_contents', to='website.hireresourcecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnDemandTeam',
            fields=[
            ],
            options={
                'verbose_name': 'On Demand Team',
                'verbose_name_plural': 'On Demand Team',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.hirepagestaticcontent',),
        ),
        migrations.CreateModel(
            name='WorldClassTalent',
            fields=[
            ],
            options={
                'verbose_name': 'World Class Talent',
                'verbose_name_plural': 'World Class Talent',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.hirepagestaticcontent',),
        ),
    ]
