# Generated by Django 3.2.8 on 2024-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_hirepagestaticcontent_ondemandteam_worldclasstalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirepagestaticcontent',
            name='content_type',
            field=models.CharField(choices=[('wct', 'World Class Talent'), ('odt', 'On Demand Team')], default='wct', max_length=3),
        ),
    ]
