# Generated by Django 3.2.8 on 2024-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_hirepagestaticcontent_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirepagestaticcontent',
            name='hire_resource_content',
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='on_demand_team',
            field=models.ManyToManyField(blank=True, related_name='on_demand_team', to='website.OnDemandTeam'),
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='world_class_talent',
            field=models.ManyToManyField(blank=True, related_name='world_class_talent', to='website.WorldClassTalent'),
        ),
    ]
