# Generated by Django 3.2.8 on 2024-07-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_auto_20240705_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='hire_resource_content',
        ),
        migrations.CreateModel(
            name='HirePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='if tag exist and set it then title will be not mandatory', max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_content', models.ManyToManyField(related_name='pricing_contents', to='website.Pricing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hireresourcecontent',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource_contents', to='website.hirepricing'),
        ),
    ]
