# Generated by Django 3.2.8 on 2024-07-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20240709_1745'),
        ('website', '0073_auto_20240705_1756'),
    ]

    operations = [
    ]
