# Generated by Django 3.2.8 on 2024-07-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_merge_0040_auto_20240709_1745_0073_auto_20240705_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomanEmpowerment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('banner_image', models.ImageField(upload_to='empowerment_banners/')),
                ('environment_title', models.CharField(blank=True, max_length=200, null=True)),
                ('environment_short_description', models.TextField(blank=True, null=True)),
                ('environment_image', models.ImageField(upload_to='work_environment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WomanInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='inspiration_images/')),
                ('empowerment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='website.womanempowerment')),
            ],
        ),
        migrations.CreateModel(
            name='WomanAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='achievement_images/')),
                ('empowerment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='website.womanempowerment')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='empowerment_photos/')),
                ('empowerment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.womanempowerment')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200)),
                ('sub_short_description', models.TextField()),
                ('icon', models.ImageField(upload_to='environment_icons/')),
                ('empowerment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='website.womanempowerment')),
            ],
        ),
    ]
