# Generated by Django 3.2.8 on 2024-07-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_csr_oureffort_ourevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csr',
            options={'verbose_name': 'CSR', 'verbose_name_plural': 'CSR'},
        ),
    ]
