# Generated by Django 3.2.8 on 2024-07-15 15:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_industrypage_industryweserve_industryweservecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryweservecontent',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryweserve',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_we_serve', to='website.industrypage'),
        ),
        migrations.AlterField(
            model_name='industryweservecontent',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_we_serve_contents', to='website.industryweserve'),
        ),
    ]
