# Generated by Django 3.2.8 on 2024-07-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_csr_oureffort_ourevent'),
        ('website', '0076_auto_20240715_1535'),
    ]

    operations = [
    ]
