# Generated by Django 3.2.8 on 2024-07-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_alter_csr_options'),
        ('website', '0077_merge_20240715_1711'),
    ]

    operations = [
    ]
