# Generated by Django 3.2.8 on 2024-07-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_environment_photo_womanachievement_womanempowerment_womaninspiration'),
        ('website', '0078_merge_0076_alter_csr_options_0077_merge_20240715_1711'),
    ]

    operations = [
    ]
