# Generated by Django 3.2.8 on 2024-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_merge_20240715_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
