# Generated by Django 3.2.8 on 2024-07-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_award_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.industrypage'),
        ),
    ]
