# Generated by Django 3.2.8 on 2024-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_industrypage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
