# Generated by Django 3.2.8 on 2024-07-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_industrypage_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('impressive_title', models.CharField(blank=True, max_length=200, null=True)),
                ('impressive_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('serve_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_areas', to='website.servecategory')),
            ],
        ),
    ]
