# Generated by Django 3.2.8 on 2024-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_applicationareas_servecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
