# Generated by Django 3.2.8 on 2024-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_industryserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryserve',
            name='serve_category',
        ),
        migrations.AddField(
            model_name='applicationareas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions_images/'),
        ),
        migrations.AddField(
            model_name='industryserve',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='industry_image_cover/'),
        ),
        migrations.AddField(
            model_name='industryserve',
            name='serve_categories',
            field=models.ManyToManyField(related_name='industries', to='website.ServeCategory'),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='industry_serve_images/'),
        ),
    ]
