# Generated by Django 3.2.8 on 2024-07-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_auto_20240725_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryserve',
            old_name='image',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='servecategory',
            old_name='image',
            new_name='industry_field_image',
        ),
    ]
