# Generated by Django 3.2.8 on 2024-07-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_auto_20240725_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryserve',
            name='serve_categories',
        ),
        migrations.AddField(
            model_name='servecategory',
            name='industry_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serve_areas', to='website.industryserve'),
        ),
    ]
