# Generated by Django 3.2.8 on 2024-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_auto_20240725_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servecategory',
            name='industry_area',
        ),
        migrations.AddField(
            model_name='industryserve',
            name='serve_categories',
            field=models.ManyToManyField(related_name='industries', to='website.ServeCategory'),
        ),
    ]
