# Generated by Django 3.2.8 on 2024-07-25 13:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_auto_20240725_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationareas',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
