# Generated by Django 3.2.8 on 2024-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_alter_applicationareas_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='industry_banner',
            field=models.ImageField(blank=True, null=True, upload_to='industry_banners/'),
        ),
    ]
