# Generated by Django 3.2.8 on 2024-07-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_servecategory_industry_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryweserve',
            name='page',
        ),
        migrations.RemoveField(
            model_name='industryweservecontent',
            name='industry',
        ),
        migrations.DeleteModel(
            name='IndustryPage',
        ),
        migrations.DeleteModel(
            name='IndustryWeServe',
        ),
        migrations.DeleteModel(
            name='IndustryWeServeContent',
        ),
    ]
