# Generated by Django 3.2.8 on 2024-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_auto_20240725_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='title_in_detail_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
