# Generated by Django 3.2.8 on 2024-07-31 14:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_servecategory_title_in_detail_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HireResourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='hire_resource_images/', verbose_name='Banner Image')),
                ('sub_title', models.TextField()),
                ('overview_title', models.CharField(max_length=255, verbose_name='Overview Title')),
                ('overview_description', models.TextField(verbose_name='Overview Description')),
                ('developer_pricing_title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('developer_pricing_sub_title', models.CharField(max_length=255, null=True, verbose_name='Sub Title')),
                ('hiring_process_title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('hiring_process_sub_title', models.CharField(max_length=255, null=True, verbose_name='Sub Title')),
                ('faq_sub_title', models.TextField(null=True, verbose_name='Sub Title')),
                ('pricing_title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('pricing_sub_title', models.CharField(max_length=255, null=True, verbose_name='Sub Title')),
                ('parents', models.ForeignKey(limit_choices_to={'is_parent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.hireresourcepage')),
            ],
            options={
                'verbose_name': 'Hire Resource',
                'verbose_name_plural': 'Hire Resources',
            },
        ),
        migrations.CreateModel(
            name='HiringStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
                ('hiring_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='website.hireresourcepage')),
            ],
        ),
        migrations.CreateModel(
            name='HireResourceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', tinymce.models.HTMLField()),
                ('hire_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='website.hireresourcepage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('hire_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='website.hireresourcepage')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperPriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jr_developer', models.CharField(max_length=255)),
                ('mid_developer', models.CharField(max_length=255)),
                ('senior_developer', models.CharField(max_length=255)),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_price_types', to='website.criteria')),
                ('hire_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_price_types', to='website.hireresourcepage')),
            ],
            options={
                'verbose_name': 'Developer Price Criteria',
                'verbose_name_plural': 'Developer Price Criteria',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255, null=True)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='website.costtype')),
                ('hire_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='website.hireresourcepage')),
            ],
            options={
                'verbose_name': 'Approx Cost',
                'verbose_name_plural': 'Approx Costs',
            },
        ),
    ]
