# Generated by Django 3.2.8 on 2024-07-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_cost_costtype_criteria_developerpricetype_faqquestion_hireresourcepage_hireresourceservice_hiringste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireresourcepage',
            name='parents',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.hireresourcepage'),
        ),
    ]
