# Generated by Django 3.2.8 on 2024-08-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0180_project_thumbnail'),
        ('website', '0095_alter_hireresourcepage_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('video', models.URLField()),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='video_testimonial/client_images/')),
                ('thumbnail', models.ImageField(upload_to='video_testimonial/thumbnails/')),
                ('designation', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
