# Generated by Django 3.2.8 on 2024-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_videotestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourgrowth',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='our_growth_icon'),
        ),
    ]
