# Generated by Django 3.2.8 on 2024-08-02 14:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_ourgrowth_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('sub_title', models.TextField()),
                ('banner_query', models.CharField(max_length=255)),
                ('development_services_title', models.CharField(max_length=255, verbose_name='Title')),
                ('development_services_sub_title', models.TextField(verbose_name='Sub Title')),
                ('faq_short_description', models.TextField(verbose_name='Short Description')),
                ('comparative_analysis_title', models.CharField(max_length=255, verbose_name='Title')),
                ('comparative_analysis_sub_title', models.TextField(verbose_name='Sub Title')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_parent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.servicepage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='website.servicepage')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
            },
        ),
        migrations.CreateModel(
            name='DiscoverOurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', tinymce.models.HTMLField()),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discover_services', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('icon', models.ImageField(upload_to='development_service_icon')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_services_process', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComparativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sapphire_software_solutions', models.CharField(max_length=255, verbose_name='Sapphire Software Solutions')),
                ('in_house', models.CharField(max_length=255, verbose_name='In-House')),
                ('freelance', models.CharField(max_length=255, verbose_name='Freelance')),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_price_types', to='website.servicecriteria')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparative_analysis', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
