# Generated by Django 3.2.8 on 2024-08-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0098_comparativeanalysis_developmentserviceprocess_discoverourservice_servicecriteria_servicefaqquestion_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeanalysis',
            name='sapphire_software_solutions',
            field=models.CharField(max_length=255, verbose_name='Mediusware Software Solutions'),
        ),
    ]
