# Generated by Django 3.2.8 on 2024-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0099_alter_comparativeanalysis_sapphire_software_solutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourgrowth',
            name='icon',
        ),
        migrations.AddField(
            model_name='ourachievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievement'),
        ),
    ]
