# Generated by Django 3.2.8 on 2024-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_auto_20240802_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryWeServe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='industry_we_serve/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
