# Generated by Django 3.2.8 on 2024-08-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_industryweserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeAtMediusware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='life_at_mediusware/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
