# Generated by Django 3.2.8 on 2024-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_blogfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='menu_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Title'),
        ),
    ]
