# Generated by Django 3.2.8 on 2024-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_servicepage_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='why_choose_us_sub_title',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Title'),
        ),
    ]
