# Generated by Django 3.2.8 on 2024-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0105_servicepage_why_choose_us_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_page/feature_images'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_page/icons'),
        ),
    ]
