# Generated by Django 3.2.8 on 2024-08-15 13:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_auto_20240813_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotestimonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
