# Generated by Django 3.2.8 on 2024-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0108_blogmoderatorfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmoderatorfeedback',
            name='created_by_title',
            field=models.IntegerField(choices=[(1, 'Moderator'), (2, 'Author')], verbose_name='Created By'),
        ),
    ]
