# Generated by Django 3.2.8 on 2024-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_alter_blogmoderatorfeedback_created_by_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'Pending'), ('2', 'Author'), ('3', 'Moderator'), ('4', 'Approved')], default='1'),
        ),
    ]
