# Generated by Django 3.2.8 on 2024-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('1', 'Pending'), ('2', 'Author'), ('3', 'Moderator'), ('4', 'Approved')], default='1'),
        ),
    ]
