# Generated by Django 3.2.8 on 2024-08-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0111_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('author', 'Author'), ('moderator', 'Moderator'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
