# Generated by Django 3.2.8 on 2024-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0112_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submit_for_review', 'Submit For Review'), ('need_revision', 'Need Revision'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
