# Generated by Django 3.2.8 on 2024-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0113_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmoderatorfeedback',
            name='created_by_title',
            field=models.IntegerField(choices=[(1, 'Moderator'), (2, 'Author')], null=True, verbose_name='Created By'),
        ),
    ]
