# Generated by Django 3.2.8 on 2024-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_alter_blogmoderatorfeedback_created_by_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submit_for_review', 'Submit For Review'), ('need_revision', 'Need Revision'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Current Status'),
        ),
    ]
