# Generated by Django 3.2.8 on 2024-08-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0115_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='office_location/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
