# Generated by Django 3.2.8 on 2024-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_officelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='active',
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'In Draft'), ('submit_for_review', 'In Review'), ('need_revision', 'In Revision'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Current Status'),
        ),
    ]
