# Generated by Django 3.2.8 on 2024-08-23 15:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0117_auto_20240822_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='LinkedIn Marketing Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Banner Youtube Video Link'),
        ),
        migrations.AlterField(
            model_name='blogcontext',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video Link'),
        ),
    ]
