# Generated by Django 3.2.8 on 2024-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0118_auto_20240823_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
