# Generated by Django 3.2.8 on 2024-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0119_auto_20240827_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatePost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.blog',),
        ),
    ]
