# Generated by Django 3.2.8 on 2024-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0122_auto_20240827_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryweserve',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
