# Generated by Django 3.2.8 on 2024-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0123_industryweserve_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'In Draft'), ('submit_for_review', 'In Review'), ('need_revision', 'In Revision'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Current Status'),
        ),
    ]
