# Generated by Django 3.2.8 on 2024-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0124_alter_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_posted',
        ),
    ]
