# Generated by Django 3.2.8 on 2024-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0125_remove_blog_is_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandphoto', models.ImageField(upload_to='brand_photos/')),
            ],
        ),
    ]
