# Generated by Django 3.2.8 on 2024-08-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0126_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
