# Generated by Django 3.2.8 on 2024-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0127_officelocation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='leads_file/'),
        ),
    ]
