# Generated by Django 3.2.8 on 2024-09-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0129_auto_20240904_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextualTestimonialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsVideoTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurJourneyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeAtMediuswareTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQHomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
