# Generated by Django 3.2.8 on 2024-09-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0130_allservicestitle_awardstitle_blogtitle_faqhometitle_industrytitle_lifeatmediuswaretitle_modeltitle_o'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WomenEmpowermentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyWeAreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSRBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClutchTestimonialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTestimonialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
    ]
