# Generated by Django 3.2.8 on 2024-09-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0131_awardsbanner_clienttestimonialbanner_clutchtestimonialbanner_contactbanner_csrbanner_deliverybanner_'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevelopmentBanner',
            new_name='DeliveryModelBanner',
        ),
        migrations.RenameModel(
            old_name='DeliveryBanner',
            new_name='DevelopmentMethodologyBanner',
        ),
        migrations.RenameModel(
            old_name='EngagementBanner',
            new_name='EngagementModelBanner',
        ),
    ]
