# Generated by Django 3.2.8 on 2024-09-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0132_auto_20240906_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='clienttestimonialbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='clutchtestimonialbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='contactbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='csrbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='deliverymodelbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='developmentmethodologybanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='engagementmodelbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='whywearebanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
        migrations.AlterField(
            model_name='womenempowermentbanner',
            name='page_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner'),
        ),
    ]
