# Generated by Django 3.2.8 on 2024-09-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0135_projectclientreviewtitle_projectkeyfeaturetitle_projectresultstitle_projectscreenshottitle_projectse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderShipBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
    ]
