# Generated by Django 3.2.8 on 2024-09-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0136_leadershipbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.TextField()),
                ('image', models.ImageField(upload_to='leadership/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadershipSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='leadership_speech/')),
                ('speech', models.TextField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.leadership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
