# Generated by Django 3.2.8 on 2024-09-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0279_alter_employee_options'),
        ('website', '0137_leadership_leadershipspeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipspeech',
            name='leadership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.leadership'),
        ),
        migrations.AlterField(
            model_name='leadershipspeech',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='employee.employee'),
        ),
    ]
