# Generated by Django 3.2.8 on 2024-09-12 11:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0279_alter_employee_options'),
        ('website', '0138_auto_20240911_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipspeech',
            name='leader',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leadershipspeech',
            name='speech',
            field=tinymce.models.HTMLField(),
        ),
    ]
