# Generated by Django 3.2.8 on 2024-09-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0139_auto_20240912_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipspeech',
            name='leadership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='website.leadership'),
        ),
    ]
