# Generated by Django 3.2.8 on 2024-09-17 20:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0140_alter_leadershipspeech_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='LinkedIn Marketing Content'),
        ),
    ]
