# Generated by Django 3.2.8 on 2024-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0141_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_calender/')),
                ('publish_date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Event Calender Automate',
                'verbose_name_plural': 'Event Calender Automate',
            },
        ),
    ]
