# Generated by Django 3.2.8 on 2024-09-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0142_eventcalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalender',
            name='publish_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published')], default='Pending', max_length=10),
        ),
    ]
