# Generated by Django 3.2.8 on 2024-09-19 12:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0143_eventcalender_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontext',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Section Description'),
        ),
        migrations.AlterField(
            model_name='blogcontext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_context_images', verbose_name='Section Image'),
        ),
        migrations.AlterField(
            model_name='blogcontext',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='blogcontext',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Section YouTube Video Link'),
        ),
    ]
