# Generated by Django 3.2.8 on 2024-09-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0282_delete_beftn'),
        ('website', '0144_auto_20240919_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='Video URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonial/thumbnails/')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='website.career')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitsOfEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='benefits')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='website.career')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
