# Generated by Django 3.2.8 on 2024-09-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0145_benefitsofemployment_career_employeetestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTestimonialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('page_banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pagebanner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitsOfEmploymentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('website_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.websitetitle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
