# Generated by Django 3.2.8 on 2024-10-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0146_benefitsofemploymenttitle_careerbanner_employeetestimonialtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='public_image/')),
            ],
        ),
    ]
