# Generated by Django 3.2.8 on 2024-10-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0147_publicimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicimage',
            options={'verbose_name_plural': 'Public Images'},
        ),
    ]
