# Generated by Django 3.2.8 on 2024-10-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0147_publicimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicimage',
            options={'verbose_name_plural': 'Public Images'},
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.blog')),
            ],
        ),
    ]
