# Generated by Django 3.2.8 on 2024-10-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0148_auto_20241011_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_blog', to='website.blog'),
        ),
    ]
