# Generated by Django 3.2.8 on 2024-10-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0148_alter_publicimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plagiarism_percentage', models.FloatField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='plagiarism_reports/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_info', to='website.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
