# Generated by Django 3.2.8 on 2024-10-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0149_plagiarisminfo'),
        ('website', '0152_hireresourcekeyword_hireresourcemetadata'),
    ]

    operations = [
    ]
