# Generated by Django 3.2.8 on 2024-10-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0153_merge_20241018_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_blog_link', models.URLField(blank=True, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_blog', to='website.blog')),
            ],
            options={
                'verbose_name_plural': 'Reference Blogs',
            },
        ),
        migrations.CreateModel(
            name='RelatedBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.blog')),
                ('releted_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releted_blog', to='website.blog')),
            ],
            options={
                'verbose_name_plural': 'Related Blogs',
            },
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
