# Generated by Django 3.2.8 on 2024-10-25 17:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0157_additionalservicecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireResourceServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hire_resource_image')),
                ('hire_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_resource', to='website.hireresourcepage')),
            ],
        ),
    ]
