# Generated by Django 3.2.8 on 2024-12-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0158_hireresourceservicecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=website.models.BlogSlugField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='BlogSEOEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Meta Title')),
                ('description', models.TextField(verbose_name='Meta Description')),
                ('keywords', models.TextField(verbose_name='Meta Keywords')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.blog')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_blogseoessential_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'SEO Essential',
                'verbose_name_plural': 'SEO Essentials',
            },
        ),
    ]
