# Generated by Django 3.2.8 on 2025-03-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0160_contact_inquiry_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_meta_data', to='website.servicepage')),
            ],
        ),
    ]
