# Generated by Django 3.2.8 on 2025-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0161_servicemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmeatadata',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hireresourcemetadata',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrymetadata',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemeatadata',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
    ]
