# Generated by Django 3.2.8 on 2025-08-01 11:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0162_auto_20250326_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time_minute',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Banner Video Link'),
        ),
        migrations.AlterField(
            model_name='blogfaq',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
