# Generated by Django 3.2.8 on 2025-08-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0164_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='website.blog'),
        ),
    ]
