# Generated by Django 3.2.8 on 2025-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0165_cta_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_body_schema',
            field=models.CharField(choices=[('Article', 'Article'), ('NewsArticle', 'News'), ('HowTo', 'How-To')], default='Article', max_length=20, verbose_name='Schema Type'),
        ),
    ]
