# Generated by Django 3.2.8 on 2025-08-01 16:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0166_blog_main_body_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('NewsArticle', 'News'), ('HowTo', 'How-To')], default='Article', max_length=20, verbose_name='Schema Type'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_body_schema',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Main Body Schema'),
        ),
    ]
