# Generated by Django 3.2.8 on 2025-08-01 18:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0167_auto_20250801_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfaq',
            name='faq_schema',
            field=tinymce.models.HTMLField(blank=True, help_text='JSON-LD format for FAQ schema, leave blank to disable schema', null=True, verbose_name='FAQ Schema'),
        ),
    ]
