# Generated by Django 3.2.8 on 2025-08-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0168_blogfaq_faq_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogfaq',
            name='faq_schema',
        ),
        migrations.CreateModel(
            name='BlogFAQSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_schema', models.TextField(blank=True, help_text='JSON-LD format for FAQ schema, leave blank to disable schema', null=True, verbose_name='FAQ Schema')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_schema', to='website.blog')),
            ],
            options={
                'verbose_name': 'Blog FAQ Schema',
                'verbose_name_plural': 'Blog FAQ Schemas',
            },
        ),
    ]
