# Generated by Django 3.2.8 on 2025-08-04 15:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0169_auto_20250801_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hightlighted_text',
            field=tinymce.models.HTMLField(blank=True, help_text='Text that will be highlighted in the blog content', null=True, verbose_name='Highlighted Text'),
        ),
    ]
