# Generated by Django 3.2.8 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0170_blog_hightlighted_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servecategory',
            options={'verbose_name': 'Industry Detail', 'verbose_name_plural': 'Industry Details'},
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
