# Generated by Django 3.2.8 on 2025-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0171_auto_20250806_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetitle',
            options={'verbose_name': 'Website Title', 'verbose_name_plural': 'Website Titles'},
        ),
        migrations.AddField(
            model_name='websitetitle',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
