# Generated by Django 3.2.8 on 2025-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0172_auto_20250806_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hireresourcepage',
            options={'verbose_name': 'Hire Developer', 'verbose_name_plural': 'Hire Developers'},
        ),
        migrations.AlterModelOptions(
            name='industryserve',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='industry_details',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='website.ServeCategory'),
        ),
    ]
