# Generated by Django 3.2.8 on 2025-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0173_auto_20250806_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='child_services',
            field=models.ManyToManyField(blank=True, related_name='blogs_as_child', to='website.ServicePage', verbose_name='Child Services'),
        ),
        migrations.AddField(
            model_name='blog',
            name='parent_services',
            field=models.ManyToManyField(limit_choices_to={'is_parent': True}, related_name='blogs_as_parent', to='website.ServicePage', verbose_name='Parent Services'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='industry_details',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='website.ServeCategory', verbose_name='Industry'),
        ),
    ]
