# Generated by Django 3.2.8 on 2025-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0174_auto_20250806_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='child_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': False}, related_name='blogs_as_child', to='website.ServicePage', verbose_name='Child Services'),
        ),
    ]
