# Generated by Django 3.2.8 on 2025-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0175_alter_blog_child_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='website.Category'),
        ),
    ]
