# Generated by Django 3.2.8 on 2025-08-07 15:30

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0177_auto_20250807_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='technology',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='technology_type', chained_model_field='type', to='website.Technology', verbose_name='Technologies'),
        ),
    ]
