# Generated by Django 3.2.8 on 2025-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0178_blog_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technologytype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
