# Generated by Django 3.2.8 on 2025-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0179_auto_20250807_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='technology',
        ),
        migrations.AddField(
            model_name='blog',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='website.Technology', verbose_name='Technologies'),
        ),
    ]
