# Generated by Django 3.2.8 on 2025-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0181_auto_20250807_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(choices=[('general', 'General Inquiry'), ('discuss', 'Discuss Service')], default='discuss', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('service_require', models.CharField(blank=True, max_length=255, null=True)),
                ('project_details', models.TextField(blank=True, null=True)),
                ('client_query', models.TextField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='contact_files/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
