# Generated by Django 3.2.8 on 2025-08-08 14:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0182_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Intro Paragraph'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='sub_title',
            field=models.TextField(verbose_name='H2 Tagline'),
        ),
    ]
