# Generated by Django 3.2.8 on 2025-08-08 16:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0183_auto_20250808_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservicecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='developmentserviceprocess',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='discoverourservice',
            name='short_description',
            field=models.TextField(verbose_name='Section Description'),
        ),
        migrations.AlterField(
            model_name='discoverourservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='comparative_analysis_sub_title',
            field=models.TextField(verbose_name='Section Description'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='comparative_analysis_title',
            field=models.CharField(max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Section Description'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='development_services_sub_title',
            field=models.TextField(verbose_name='Section Description'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='development_services_title',
            field=models.CharField(max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='menu_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='sub_title',
            field=models.TextField(verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='why_choose_us_sub_title',
            field=models.TextField(blank=True, null=True, verbose_name='Section Description'),
        ),
        migrations.CreateModel(
            name='ServiceCategoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for FAQs')),
                ('serve_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.servecategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
