# Generated by Django 3.2.8 on 2025-08-08 18:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0184_auto_20250808_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategoryfaq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': "FAQ's"},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='servicecategoryfaq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='servicefaqquestion',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='TechnologyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for FAQs')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.technology')),
            ],
            options={
                'verbose_name': 'Technology FAQ',
                'verbose_name_plural': 'Technology FAQs',
                'ordering': ['order'],
            },
        ),
    ]
