# Generated by Django 3.2.8 on 2025-08-08 18:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0185_auto_20250808_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyfaq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
