# Generated by Django 3.2.8 on 2025-08-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0190_servecategoryfaqschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyFAQSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_schema', models.TextField(help_text='JSON-LD schema for FAQs')),
                ('serve_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_schema', to='website.technology')),
            ],
        ),
    ]
