# Generated by Django 3.2.8 on 2025-08-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0191_technologyfaqschema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologyfaqschema',
            old_name='serve_category',
            new_name='technology',
        ),
    ]
