# Generated by Django 3.2.8 on 2025-08-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0192_rename_serve_category_technologyfaqschema_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageFAQSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_schema', models.TextField(help_text='JSON-LD schema for FAQs')),
                ('service_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_schema', to='website.servicepage')),
            ],
        ),
    ]
