# Generated by Django 3.2.8 on 2025-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0193_servicepagefaqschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='If checked, this technology will be displayed in the main menu.'),
        ),
    ]
