# Generated by Django 3.2.8 on 2025-08-13 17:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0194_technology_show_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='benefits_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions_images/')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryDetailsHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='industry_details_images/')),
            ],
        ),
        migrations.CreateModel(
            name='OurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='why_choose_us_images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
