# Generated by Django 3.2.8 on 2025-08-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0195_auto_20250813_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='website.servecategory'),
        ),
        migrations.AddField(
            model_name='customsolutions',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_solutions', to='website.servecategory'),
        ),
        migrations.AddField(
            model_name='industrydetailsheading',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_details_heading', to='website.servecategory'),
        ),
        migrations.AddField(
            model_name='ourprocess',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_process', to='website.servecategory'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='website.servecategory'),
        ),
    ]
