# Generated by Django 3.2.8 on 2025-08-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0196_auto_20250813_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='customsolutions',
            options={'verbose_name': 'Custom Solution', 'verbose_name_plural': 'Custom Solutions'},
        ),
        migrations.AlterModelOptions(
            name='industrydetailsheading',
            options={'verbose_name': 'Industry Details Heading', 'verbose_name_plural': 'Industry Details Headings'},
        ),
        migrations.AlterModelOptions(
            name='ourprocess',
            options={'ordering': ['order'], 'verbose_name': 'Our Process', 'verbose_name_plural': 'Our Processes'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
