# Generated by Django 3.2.8 on 2025-08-15 12:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0199_industrydetailsheadingcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSolutionsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions_images/')),
                ('custom_solutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_solutions_cards', to='website.customsolutions')),
            ],
        ),
    ]
