# Generated by Django 3.2.8 on 2025-08-15 19:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0203_solutionsandservices_solutionsandservicescards'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='benefits_images/')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KeyThings', to='website.servicepage')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='KeyThingsQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('benefits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KeyThings_cards', to='website.keythings')),
            ],
        ),
    ]
