# Generated by Django 3.2.8 on 2025-08-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0204_keythings_keythingsqa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keythings',
            options={'verbose_name': 'Key Things', 'verbose_name_plural': 'Key Things'},
        ),
    ]
