# Generated by Django 3.2.8 on 2025-08-18 11:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0205_alter_keythings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPracticesCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BestPracticesHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('service_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_practices', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BestPracticesCardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('best_practices_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='website.bestpracticescards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bestpracticescards',
            name='best_practices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='website.bestpracticesheadings'),
        ),
    ]
