# Generated by Django 3.2.8 on 2025-08-18 12:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0206_auto_20250818_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('service_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_choose_us', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesWhyChooseUsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_choose_us_images/')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('services_why_choose_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='website.serviceswhychooseus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesWhyChooseUsCardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('services_why_choose_us_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='website.serviceswhychooseuscards')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
