# Generated by Django 3.2.8 on 2025-08-18 12:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0207_serviceswhychooseus_serviceswhychooseuscards_serviceswhychooseuscardsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesOurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_process', to='website.servicepage')),
            ],
            options={
                'verbose_name': 'Our Process',
                'verbose_name_plural': 'Our Processes',
                'ordering': ['order'],
            },
        ),
    ]
