# Generated by Django 3.2.8 on 2025-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0208_servicesourprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceswhychooseuscards',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display for process steps'),
        ),
    ]
