# Generated by Django 3.2.8 on 2025-08-18 17:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0209_serviceswhychooseuscards_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologySolutionsAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions_and_services', to='website.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologySolutionsAndServicesCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('solutions_and_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='website.technologysolutionsandservices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
