# Generated by Django 3.2.8 on 2025-08-18 18:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0210_technologysolutionsandservices_technologysolutionsandservicescards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesWeProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_we_provide', to='website.servecategory')),
            ],
            options={
                'verbose_name': 'Industry Details Heading',
                'verbose_name_plural': 'Industry Details Headings',
            },
        ),
        migrations.CreateModel(
            name='ServicesWeProvideCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('provides', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_we_provide_cards', to='website.servicesweprovide')),
            ],
        ),
    ]
