# Generated by Django 3.2.8 on 2025-08-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0211_servicesweprovide_servicesweprovidecards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesweprovide',
            options={'verbose_name': 'Services We Provide Heading', 'verbose_name_plural': 'Services We Provide Headings'},
        ),
        migrations.AlterField(
            model_name='servicesweprovide',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_we_provide', to='website.technology'),
        ),
    ]
