# Generated by Django 3.2.8 on 2025-08-18 18:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0212_auto_20250818_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem', to='website.technology')),
            ],
            options={
                'verbose_name': 'EcoSystem Heading',
                'verbose_name_plural': 'EcoSystem Headings',
            },
        ),
        migrations.CreateModel(
            name='EcoSystemCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('ecosystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_cards', to='website.ecosystem')),
            ],
        ),
        migrations.CreateModel(
            name='EcoSystemCardTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('ecosystem_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_card_tags', to='website.ecosystemcards')),
            ],
        ),
    ]
