# Generated by Django 3.2.8 on 2025-08-18 18:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0213_ecosystem_ecosystemcards_ecosystemcardtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyKeyThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KeyThings', to='website.technology')),
            ],
            options={
                'verbose_name': 'Key Things',
                'verbose_name_plural': 'Key Things',
            },
        ),
        migrations.CreateModel(
            name='TechnologyKeyThingsQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('key_things', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KeyThings_cards', to='website.technologykeythings')),
            ],
        ),
    ]
