# Generated by Django 3.2.8 on 2025-08-18 18:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0214_technologykeythings_technologykeythingsqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('service_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_choose_us', to='website.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyWhyChooseUsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_choose_us_images/')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('services_why_choose_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='website.technologywhychooseus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='technologykeythingsqa',
            name='key_things',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tech_KeyThings_cards', to='website.technologykeythings'),
        ),
        migrations.CreateModel(
            name='TechnologyWhyChooseUsCardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('services_why_choose_us_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='website.technologywhychooseuscards')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
