# Generated by Django 3.2.8 on 2025-08-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0215_auto_20250818_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologywhychooseuscardsdetails',
            name='services_why_choose_us_cards',
        ),
        migrations.RemoveField(
            model_name='technologywhychooseus',
            name='service_page',
        ),
        migrations.AddField(
            model_name='technologywhychooseus',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tech_why_choose_us', to='website.technology'),
        ),
        migrations.DeleteModel(
            name='TechnologyWhyChooseUsCards',
        ),
        migrations.DeleteModel(
            name='TechnologyWhyChooseUsCardsDetails',
        ),
    ]
