# Generated by Django 3.2.8 on 2025-08-18 18:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0216_auto_20250818_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyWhyChooseUsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_choose_us_images/')),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('tech_why_choose_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tech_why_choose_us_cards', to='website.technologywhychooseus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyWhyChooseUsCardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('tech_why_choose_us_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_why_choose_us_card_details', to='website.technologywhychooseuscards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyOurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_process', to='website.technology')),
            ],
            options={
                'verbose_name': 'Our Process',
                'verbose_name_plural': 'Our Processes',
                'ordering': ['order'],
            },
        ),
    ]
