# Generated by Django 3.2.8 on 2025-08-19 12:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0217_technologyourprocess_technologywhychooseuscards_technologywhychooseuscardsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='history_of_tech_images/')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_of_tech', to='website.technology')),
            ],
            options={
                'verbose_name': 'History of Technology',
                'verbose_name_plural': 'History of Technologies',
            },
        ),
    ]
