# Generated by Django 3.2.8 on 2025-08-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0218_historyoftech'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Title'),
        ),
    ]
