# Generated by Django 3.2.8 on 2025-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0219_servicepage_secondary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Title'),
        ),
    ]
