# Generated by Django 3.2.8 on 2025-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0220_servecategory_secondary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
