# Generated by Django 3.2.8 on 2025-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0221_blog_cta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA Title'),
        ),
    ]
