# Generated by Django 3.2.8 on 2025-08-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0222_alter_blog_cta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cta',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servecategorycta',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicepagecta',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technologycta',
            name='description',
        ),
    ]
