# Generated by Django 3.2.8 on 2025-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0223_auto_20250820_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='menu_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Title'),
        ),
    ]
