# Generated by Django 3.2.8 on 2025-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0224_auto_20250821_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Show in Menu'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='menu_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Title2'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Menu Title'),
        ),
    ]
