# Generated by Django 3.2.8 on 2025-08-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0225_auto_20250821_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='comparative_analysis_sub_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='comparative_analysis_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='development_services_sub_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='development_services_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='faq_short_description',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='menu_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='why_choose_us_sub_title',
        ),
    ]
