# Generated by Django 3.2.8 on 2025-08-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0226_auto_20250821_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='child_services',
        ),
    ]
