# Generated by Django 3.2.8 on 2025-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0227_remove_blog_child_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydetailsherosection',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
