# Generated by Django 3.2.8 on 2025-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0228_industrydetailsherosection_secondary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyoftech',
            name='section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
