# Generated by Django 3.2.8 on 2025-08-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0229_alter_historyoftech_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO purposes', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True)),
                ('service_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_description', to='website.servicepage')),
            ],
        ),
    ]
