# Generated by Django 3.2.8 on 2025-08-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0230_metadescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCreatorsQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='creator_quotes_images/')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators_quotes', to='website.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
