# Generated by Django 3.2.8 on 2025-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0231_technologycreatorsquotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
    ]
