# Generated by Django 3.2.8 on 2025-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0232_servecategory_seo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servecategory',
            name='impressive_description',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='impressive_title',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='industry_banner',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='industry_field_image',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='title_in_detail_page',
        ),
        migrations.AlterField(
            model_name='servecategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Section Title'),
        ),
        migrations.DeleteModel(
            name='IndustryKeyword',
        ),
    ]
