# Generated by Django 3.2.8 on 2025-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0233_auto_20250825_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Title'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='bestpracticesheadings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='customsolutions',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='ecosystem',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='historyoftech',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='industrydetailsheading',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='industrydetailsherosection',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='keythings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='servicesweprovide',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='serviceswhychooseus',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='solutionsandservices',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='technologykeythings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='technologysolutionsandservices',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='technologywhychooseus',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
    ]
