# Generated by Django 3.2.8 on 2025-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0234_auto_20250825_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologysolutionsandservices',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='secondary_title',
        ),
        migrations.AddField(
            model_name='technologysolutionsandservices',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Secondary Title'),
        ),
    ]
