# Generated by Django 3.2.8 on 2025-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0236_technologymetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='impressive_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='impressive_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='industry_banner',
            field=models.ImageField(blank=True, null=True, upload_to='industry_banners/'),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='industry_field_image',
            field=models.ImageField(blank=True, null=True, upload_to='industry_serve_images/'),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servecategory',
            name='title_in_detail_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
