# Generated by Django 3.2.8 on 2025-08-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0236_technologymetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='services_body_schema',
            field=models.TextField(blank=True, help_text='JSON-LD schema for Service Page body', null=True),
        ),
    ]
