# Generated by Django 3.2.8 on 2025-08-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0237_auto_20250825_1807'),
        ('website', '0237_servicepage_services_body_schema'),
    ]

    operations = [
    ]
