# Generated by Django 3.2.8 on 2025-08-27 11:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0238_merge_20250826_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servecategory',
            name='impressive_description',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='impressive_title',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='industry_banner',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='industry_field_image',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='servecategory',
            name='title_in_detail_page',
        ),
        migrations.RemoveField(
            model_name='whychooseuscards',
            name='card_description',
        ),
        migrations.AddField(
            model_name='whychooseuscards',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us_images/'),
        ),
        migrations.AddField(
            model_name='whychooseuscards',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display for process steps'),
        ),
        migrations.CreateModel(
            name='WhyChooseUsCardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('why_choose_us_cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us_cards_details', to='website.whychooseuscards')),
            ],
        ),
    ]
