# Generated by Django 3.2.8 on 2025-08-27 15:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0239_auto_20250827_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPageHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secodary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalPageKeyThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatIsNext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(max_length=255, verbose_name='SEO Title')),
                ('section_title', models.CharField(max_length=255)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalPageWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('additional_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_page_why_choose_us', to='website.additionalpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalPageOurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('additional_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_process', to='website.additionalpages')),
            ],
            options={
                'verbose_name': 'Our Process',
                'verbose_name_plural': 'Our Processes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPageKeyThingsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', models.TextField(blank=True, null=True)),
                ('additional_page_key_things', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_page_key_things_cards', to='website.additionalpagekeythings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='additionalpagekeythings',
            name='additional_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_page_key_things', to='website.additionalpages'),
        ),
        migrations.CreateModel(
            name='AdditionalPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', tinymce.models.HTMLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for FAQs')),
                ('additional_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.additionalpages')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
