# Generated by Django 3.2.8 on 2025-08-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0240_auto_20250827_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalpageherosection',
            name='additional_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_page_hero_section', to='website.additionalpages'),
        ),
    ]
