# Generated by Django 3.2.8 on 2025-08-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0241_additionalpageherosection_additional_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatisnext',
            name='additional_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='what_is_next', to='website.additionalpages'),
        ),
    ]
