# Generated by Django 3.2.8 on 2025-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0242_whatisnext_additional_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatIsNext',
            new_name='WhatIs',
        ),
        migrations.RemoveField(
            model_name='additionalpageherosection',
            name='slug',
        ),
    ]
