# Generated by Django 3.2.8 on 2025-08-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0243_auto_20250827_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(max_length=100)),
                ('section_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Award Categories',
            },
        ),
        migrations.CreateModel(
            name='AwardYearGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_groups', to='website.awardcategory')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='website.awardyeargroup')),
            ],
        ),
    ]
