# Generated by Django 3.2.8 on 2025-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0244_awardcategory_awards_awardyeargroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcategory',
            options={'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AddField(
            model_name='awards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='awards/'),
        ),
        migrations.AddField(
            model_name='awards',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='awards',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Award URL'),
        ),
    ]
