# Generated by Django 3.2.8 on 2025-08-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0245_auto_20250828_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologycreatorsquotes',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creators_quotes', to='website.technology'),
        ),
        migrations.AlterField(
            model_name='technologysolutionsandservicescards',
            name='solutions_and_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.technologysolutionsandservices'),
        ),
        migrations.AlterField(
            model_name='technologywhychooseus',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tech_why_choose_us', to='website.technology'),
        ),
        migrations.AlterField(
            model_name='technologywhychooseuscards',
            name='tech_why_choose_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tech_why_choose_us_cards', to='website.technologywhychooseus'),
        ),
        migrations.AlterField(
            model_name='technologywhychooseuscardsdetails',
            name='tech_why_choose_us_cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_why_choose_us_card_details', to='website.technologywhychooseuscards'),
        ),
    ]
