# Generated by Django 3.2.8 on 2025-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0246_auto_20250829_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydetailsherosection',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='technology_featured_images/'),
        ),
        migrations.AddField(
            model_name='technology',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='technology_featured_images/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title'),
        ),
    ]
