# Generated by Django 3.2.8 on 2025-09-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0248_homepage_homepageheroanimatedtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesItemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('service_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_item_tags', to='website.servicepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
