# Generated by Django 3.2.8 on 2025-09-09 13:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0249_servicesitemtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipspeech',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadershipspeech',
            name='speech',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
