# Generated by Django 3.2.8 on 2025-09-09 13:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0250_auto_20250909_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipspeech',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
