# Generated by Django 3.2.8 on 2025-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0251_alter_leadershipspeech_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Certification URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Certification Link')),
            ],
        ),
    ]
