# Generated by Django 3.2.8 on 2025-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0252_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Certification Image URL'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
    ]
