# Generated by Django 3.2.8 on 2025-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0253_auto_20250909_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='parent_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': True}, related_name='blogs_as_parent', to='website.ServicePage', verbose_name='Services'),
        ),
    ]
