# Generated by Django 3.2.8 on 2025-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0254_alter_blog_parent_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Show in Menu'),
        ),
    ]
