# Generated by Django 3.2.8 on 2025-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0256_auto_20250910_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalpages',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='additionalpages',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
    ]
