# Generated by Django 3.2.8 on 2025-09-11 13:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0257_auto_20250911_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpageherosection',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpagekeythings',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpagekeythingscards',
            name='card_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatis',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
