# Generated by Django 3.2.8 on 2025-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0258_auto_20250911_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpageourprocess',
            name='section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whatis',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatis',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title'),
        ),
    ]
