# Generated by Django 3.2.8 on 2025-09-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0338_alter_employeesocial_title'),
        ('website', '0259_auto_20250911_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='employee.employee'),
        ),
    ]
