# Generated by Django 3.2.8 on 2025-09-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0338_alter_employeesocial_title'),
        ('website', '0260_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='BeginningOfWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Title')),
                ('section_description', models.TextField(blank=True, null=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning_of_working', to='website.homepage')),
            ],
        ),
    ]
