# Generated by Django 3.2.8 on 2025-09-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0261_auto_20250918_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryWeServeHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_we_serve', to='website.homepage')),
            ],
        ),
    ]
