# Generated by Django 3.2.8 on 2025-09-18 17:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0263_awardshomepage_blogsandarticleshomepage_casestudyhomepage_techstack_testimonialshomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProcessHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for process steps')),
                ('home_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_process_home', to='website.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
