# Generated by Django 3.2.8 on 2025-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0265_teamelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='servecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='industry_icons/'),
        ),
    ]
