# Generated by Django 3.2.8 on 2025-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0266_servecategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydetailsherosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='industry_details_images/', verbose_name='Icon'),
        ),
    ]
