# Generated by Django 3.2.8 on 2025-09-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0267_alter_industrydetailsherosection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesRelatedBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_related_blogs', to='website.servicepage')),
            ],
            options={
                'verbose_name': 'Related Blog',
                'verbose_name_plural': 'Related Blogs',
            },
        ),
    ]
