# Generated by Django 3.2.8 on 2025-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0269_archivepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireDeveloperPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='hire_developer_page')),
            ],
        ),
        migrations.AlterModelOptions(
            name='archivepage',
            options={'verbose_name': 'Page Hero Section', 'verbose_name_plural': 'Page Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
    ]
