# Generated by Django 3.2.8 on 2025-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0270_auto_20250929_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModuleIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
