# Generated by Django 3.2.8 on 2025-09-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0271_deliverymoduleintro'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymoduleintro',
            name='hire_developer_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_module_intros', to='website.hiredeveloperpage'),
        ),
    ]
