# Generated by Django 3.2.8 on 2025-09-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0272_deliverymoduleintro_hire_developer_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('hire_developer_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_mechanisms', to='website.hiredeveloperpage')),
            ],
        ),
    ]
