# Generated by Django 3.2.8 on 2025-09-29 12:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0273_workingmechanism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymoduleintro',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiredeveloperpage',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workingmechanism',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
