# Generated by Django 3.2.8 on 2025-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0278_hiringcomparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringThroughMediusware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_developer_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_through_mediuswares', to='website.hiringcomparison')),
            ],
        ),
        migrations.CreateModel(
            name='HiringFreeLancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_freelancers', to='website.hiringcomparison')),
            ],
        ),
    ]
