# Generated by Django 3.2.8 on 2025-09-29 15:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0279_hiringfreelancer_hiringthroughmediusware'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('hiring_comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_guides', to='website.hiredeveloperpage')),
            ],
        ),
    ]
