# Generated by Django 3.2.8 on 2025-09-29 15:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0280_comprehensiveguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveGuideSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('comprehensive_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_guide_sections', to='website.comprehensiveguide')),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveGuideSectionQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', tinymce.models.HTMLField(blank=True, null=True)),
                ('comprehensive_guide_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_guide_section_points', to='website.comprehensiveguidesections')),
            ],
        ),
    ]
