# Generated by Django 3.2.8 on 2025-09-29 15:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0282_definingdevelopersrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefiningDevelopersRole',
            new_name='DefiningDevelopers',
        ),
        migrations.CreateModel(
            name='DefiningDeveloperCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('defining_developer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defining_developer_cards', to='website.definingdevelopers')),
            ],
        ),
    ]
