# Generated by Django 3.2.8 on 2025-09-29 16:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0284_qualities_qualitycards'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireDeveloperFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', tinymce.models.HTMLField(blank=True, null=True)),
                ('hire_developer_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.hiredeveloperpage')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': "FAQ's",
            },
        ),
    ]
