# Generated by Django 3.2.8 on 2025-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0285_hiredeveloperfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireDeveloperMetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meta Description',
                'verbose_name_plural': 'Meta Descriptions',
            },
        ),
    ]
