# Generated by Django 3.2.8 on 2025-09-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0286_hiredevelopermetadescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredevelopermetadescription',
            name='hire_developer_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_descriptions', to='website.hiredeveloperpage'),
        ),
    ]
