# Generated by Django 3.2.8 on 2025-09-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0287_hiredevelopermetadescription_hire_developer_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benifitcards',
            options={'verbose_name': 'Benifit Card', 'verbose_name_plural': 'Benifit Cards'},
        ),
        migrations.AlterModelOptions(
            name='benifits',
            options={'verbose_name': 'Benifit', 'verbose_name_plural': 'Benifits'},
        ),
        migrations.AlterModelOptions(
            name='comprehensiveguide',
            options={'verbose_name': 'Comprehensive Guide', 'verbose_name_plural': 'Comprehensive Guides'},
        ),
        migrations.AlterModelOptions(
            name='comprehensiveguidesectionqna',
            options={'verbose_name': 'Comprehensive Guide Section QnA', 'verbose_name_plural': 'Comprehensive Guide Section QnA'},
        ),
        migrations.AlterModelOptions(
            name='comprehensiveguidesections',
            options={'verbose_name': 'Comprehensive Guide Section', 'verbose_name_plural': 'Comprehensive Guide Sections'},
        ),
        migrations.AlterModelOptions(
            name='definingdevelopercards',
            options={'verbose_name': 'Defining Developer Card', 'verbose_name_plural': 'Defining Developer Cards'},
        ),
        migrations.AlterModelOptions(
            name='definingdevelopers',
            options={'verbose_name': 'Defining Developer', 'verbose_name_plural': 'Defining Developers'},
        ),
        migrations.AlterModelOptions(
            name='deliverymoduleintro',
            options={'verbose_name': 'Delivery Module Intro', 'verbose_name_plural': 'Delivery Module Intro'},
        ),
        migrations.AlterModelOptions(
            name='hiredevelopersourprocess',
            options={'verbose_name': 'Our Process', 'verbose_name_plural': 'Our Processes'},
        ),
        migrations.AlterModelOptions(
            name='hiringcomparison',
            options={'verbose_name': 'Hiring Comparison', 'verbose_name_plural': 'Hiring Comparisons'},
        ),
        migrations.AlterModelOptions(
            name='hiringfreelancer',
            options={'verbose_name': 'Hiring FreeLancer', 'verbose_name_plural': 'Hiring FreeLancer'},
        ),
        migrations.AlterModelOptions(
            name='hiringthroughmediusware',
            options={'verbose_name': 'Hiring Through Mediusware', 'verbose_name_plural': 'Hiring Through Mediusware'},
        ),
        migrations.AlterModelOptions(
            name='qualities',
            options={'verbose_name': 'Quality', 'verbose_name_plural': 'Qualities'},
        ),
        migrations.AlterModelOptions(
            name='qualitycards',
            options={'verbose_name': 'Quality Card', 'verbose_name_plural': 'Quality Cards'},
        ),
        migrations.AlterModelOptions(
            name='workingmechanism',
            options={'verbose_name': 'Working Mechanism', 'verbose_name_plural': 'Working Mechanism'},
        ),
    ]
