# Generated by Django 3.2.8 on 2025-09-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0288_auto_20250929_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiredevelopermetadescription',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Meta'},
        ),
    ]
