# Generated by Django 3.2.8 on 2025-09-29 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0289_alter_hiredevelopermetadescription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringfreelancer',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiringthroughmediusware',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True),
        ),
    ]
