# Generated by Django 3.2.8 on 2025-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0290_auto_20250929_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepage',
            name='seo_title',
            field=models.CharField(blank=True, default='Sample SEO Title', max_length=200, null=True, verbose_name='SEO Title'),
        ),
    ]
