# Generated by Django 3.2.8 on 2025-09-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0291_alter_archivepage_seo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiredeveloperpage',
            options={'verbose_name': 'Hire Developer', 'verbose_name_plural': 'Hire Developer'},
        ),
    ]
