# Generated by Django 3.2.8 on 2025-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0292_alter_hiredeveloperpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
