# Generated by Django 3.2.8 on 2025-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0293_archivepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingmechanism',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
