# Generated by Django 3.2.8 on 2025-09-30 16:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0294_workingmechanism_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingMechanismCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Order of display for working mechanism cards', null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('working_mechanism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_mechanism_cards', to='website.workingmechanism')),
            ],
            options={
                'verbose_name': 'Working Mechanism Card',
                'verbose_name_plural': 'Working Mechanism Cards',
            },
        ),
    ]
