# Generated by Django 3.2.8 on 2025-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0295_workingmechanismcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='action_by',
            field=models.CharField(choices=[('pending', 'Pending'), ('sales', 'Sales'), ('hr', 'HR')], default='pending', max_length=50),
        ),
    ]
