# Generated by Django 3.2.8 on 2025-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0296_contactform_action_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='action_by',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sales', 'Sales'), ('hr', 'HR')], default='pending', max_length=50, null=True),
        ),
    ]
