# Generated by Django 3.2.8 on 2025-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0297_alter_contactform_action_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='client_query',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='project_details',
        ),
        migrations.AddField(
            model_name='contactform',
            name='short_brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
