# Generated by Django 3.2.8 on 2025-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0298_auto_20251001_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='action_by',
            field=models.CharField(blank=True, choices=[('pending', '⌛ Pending'), ('sales', '💼 Sales'), ('hr', '🤝 HR')], default='pending', max_length=50, null=True),
        ),
    ]
