# Generated by Django 3.2.8 on 2025-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0299_alter_contactform_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
