# Generated by Django 3.2.8 on 2025-10-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0300_contactform_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceblogs',
            name='reference_blog_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
