# Generated by Django 3.2.8 on 2025-10-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0301_referenceblogs_reference_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceblogs',
            name='reference_blog_id',
        ),
    ]
