# Generated by Django 3.2.8 on 2025-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0302_remove_referenceblogs_reference_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrelatedblogs',
            name='blog_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
