# Generated by Django 3.2.8 on 2025-10-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0305_technologyrelatedblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPageRelatedBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_page_related_blogs', to='website.additionalpages')),
            ],
            options={
                'verbose_name': 'Related Blog',
                'verbose_name_plural': 'Related Blogs',
            },
        ),
    ]
