# Generated by Django 3.2.8 on 2025-10-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0306_additionalpagerelatedblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivepage',
            options={'verbose_name': 'All Page', 'verbose_name_plural': 'All Pages'},
        ),
    ]
