# Generated by Django 3.2.8 on 2025-10-08 12:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0307_alter_archivepage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePageBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('archive_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_page_bodies', to='website.archivepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
