# Generated by Django 3.2.8 on 2025-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0282_project_case_study_pdf'),
        ('website', '0308_archivepagebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetadata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_metadata', to='project_management.project'),
        ),
    ]
