# Generated by Django 3.2.8 on 2025-10-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0309_alter_projectmetadata_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('starter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_title', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_title', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
