# Generated by Django 3.2.8 on 2025-10-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0311_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pricing_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.pricingtable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='display_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='pricing_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='website.pricingtable'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingplan',
            unique_together={('pricing_table', 'plan_type')},
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='plan_title',
        ),
        migrations.CreateModel(
            name='PricingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean')], default='text', max_length=10)),
                ('text_value', models.CharField(blank=True, max_length=255)),
                ('boolean_value', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='website.pricingfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='website.pricingplan')),
            ],
            options={
                'unique_together': {('feature', 'plan')},
            },
        ),
    ]
