# Generated by Django 3.2.8 on 2025-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0312_auto_20251020_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingvalue',
            name='boolean_value',
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
