# Generated by Django 3.2.8 on 2025-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0313_auto_20251020_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingfeature',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='pricingvalue',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
