# Generated by Django 3.2.8 on 2025-10-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0314_auto_20251020_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingvalue',
            unique_together={('feature',)},
        ),
        migrations.RemoveField(
            model_name='pricingvalue',
            name='plan',
        ),
    ]
