# Generated by Django 3.2.8 on 2025-10-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0315_auto_20251020_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
