# Generated by Django 3.2.8 on 2025-10-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0316_delete_pricingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingvalue',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingvalue',
            name='value_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('boolean', 'Boolean')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pricingvalue',
            unique_together=set(),
        ),
    ]
