# Generated by Django 3.2.8 on 2025-10-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0317_auto_20251020_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingfeature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricingvalue',
            name='feature',
        ),
        migrations.CreateModel(
            name='FeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pricing_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='website.pricingfeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricingvalue',
            name='feature_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='website.featurename'),
        ),
    ]
