# Generated by Django 3.2.8 on 2025-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0319_auto_20251020_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingvalue',
            name='text_value',
            field=models.CharField(blank=True, help_text="Enter text if value type is 'text'; otherwise write true/false or 1/0.", max_length=255),
        ),
        migrations.AlterField(
            model_name='pricingvalue',
            name='value_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('boolean', 'True/False')], help_text='Indicates whether the value is text or boolean', max_length=10, null=True),
        ),
    ]
