# Generated by Django 3.2.8 on 2025-10-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0321_pricingtableheader_servicenameforpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingfeature',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_features', to='website.servicenameforpricing'),
        ),
    ]
