# Generated by Django 3.2.8 on 2025-10-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0322_pricingfeature_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeaturesColumnsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=255)),
                ('pricing_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_columns_content', to='website.pricingfeature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
