# Generated by Django 3.2.8 on 2025-10-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0323_pricingfeaturescolumnsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeaturesColumnsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, help_text='Cell content for this column', null=True)),
                ('column_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='website.pricingfeaturescolumnsname')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pricingtableheader', verbose_name='Pricing Column')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
