# Generated by Django 3.2.8 on 2025-10-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0324_pricingfeaturescolumnscontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurename',
            name='pricing_feature',
        ),
        migrations.AddField(
            model_name='featurename',
            name='pricing_features_columns_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_names', to='website.pricingfeaturescolumnsname'),
        ),
        migrations.AlterField(
            model_name='pricingfeaturescolumnscontent',
            name='header',
            field=models.ForeignKey(help_text='Select the pricing column this content belongs to', on_delete=django.db.models.deletion.CASCADE, to='website.pricingtableheader', verbose_name='Pricing Column'),
        ),
    ]
