# Generated by Django 3.2.8 on 2025-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0326_remove_pricingfeature_pricing_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurename',
            options={'verbose_name': 'Sub Feature Name', 'verbose_name_plural': 'Sub Feature Name'},
        ),
        migrations.AlterModelOptions(
            name='pricingfeaturescolumnscontent',
            options={'verbose_name': 'Pricing Feature Row Content', 'verbose_name_plural': 'Pricing Feature Row Contents'},
        ),
        migrations.AlterModelOptions(
            name='pricingfeaturescolumnsname',
            options={'verbose_name': 'Pricing Parent Feature Name', 'verbose_name_plural': 'Pricing Parent Feature Name'},
        ),
    ]
