# Generated by Django 3.2.8 on 2025-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0327_auto_20251029_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='blog_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Blog URL'),
        ),
    ]
