# Generated by Django 3.2.8 on 2025-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0328_awards_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ins_link',
            field=models.URLField(blank=True, null=True, verbose_name='Inspiration Link'),
        ),
    ]
