# Generated by Django 3.2.8 on 2025-12-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0329_blog_ins_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
