# Generated by Django 3.2.8 on 2025-12-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0330_ctabuttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_cta', to='website.ctabuttons'),
        ),
    ]
