# Generated by Django 3.2.8 on 2025-12-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0331_homepage_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta',
        ),
    ]
