# Generated by Django 3.2.8 on 2025-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0332_remove_homepage_cta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CTAButtons',
        ),
        migrations.AddField(
            model_name='beginningofworking',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beginningofworking',
            name='cta_button_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
