# Generated by Django 3.2.8 on 2025-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0333_auto_20251223_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryweservehomepage',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryweservehomepage',
            name='cta_button_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
