# Generated by Django 3.2.8 on 2025-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0336_auto_20251223_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardshomepage',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='awardshomepage',
            name='cta_button_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
