# Generated by Django 3.2.8 on 2025-12-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0340_blogviewlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogviewlog',
            options={'verbose_name': 'Blog View Log', 'verbose_name_plural': 'Blog View Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='blogviewlog',
            unique_together={('blog', 'ip_address', 'country')},
        ),
    ]
