# Generated by Django 3.2.8 on 2025-12-25 12:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0343_yoursuccesstop3percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourSuccessTop3PercentCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('success_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_cards', to='website.yoursuccesstop3percent')),
            ],
        ),
    ]
