# Generated by Django 3.2.8 on 2025-12-25 12:33

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0344_yoursuccesstop3percentcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenifitsTop3Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('top_3_percent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benifits_points', to='website.top3percent')),
            ],
        ),
    ]
