# Generated by Django 3.2.8 on 2025-12-25 12:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0345_benifitstop3percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenifitsTop3PercentCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='benifits_top3percent/')),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('benifits_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benifits_top3percent_cards', to='website.benifitstop3percent')),
            ],
        ),
    ]
