# Generated by Django 3.2.8 on 2025-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0346_benifitstop3percentcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='benifitstop3percent',
            name='cta_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benifitstop3percent',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yoursuccesstop3percent',
            name='cta_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yoursuccesstop3percent',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
