# Generated by Django 3.2.8 on 2025-12-25 13:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0348_needmoredevtop3percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedMoreDevTop3PercentCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('need_more_dev_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_more_dev_top3percent_cards', to='website.needmoredevtop3percent')),
            ],
        ),
    ]
