# Generated by Django 3.2.8 on 2025-12-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0357_employeesnack_snacknote'),
        ('website', '0349_needmoredevtop3percentcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoredevtop3percentcards',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_speeches', to='employee.employee'),
        ),
    ]
