# Generated by Django 3.2.8 on 2025-12-26 11:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0351_flexibilitytop3percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibilityTop3PercentCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('section_title', tinymce.models.HTMLField(blank=True, null=True)),
                ('section_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('section_gif', models.ImageField(blank=True, null=True, upload_to='flexibility_top3percent/')),
                ('flexibility_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexibility_top3percent_cards', to='website.flexibilitytop3percent')),
            ],
        ),
    ]
