from .employee import EmployeeAdmin
from .leave import LeaveManagement
from .overtime import OvertimeAdmin
from .resignation import ResignationAdmin
from .user import UserAdmin
from .skill import SkillAdmin
from .employee_activity import *
from .employee_feedback import EmployeeFeedbackAdmin
from .tour_allowance import TourAllowanceAdmin
