# Generated by Django 3.2.8 on 2023-10-27 19:46

from django.db import migrations, models
import project_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0106_auto_20231010_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=project_management.models.create_project_identifier, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='update',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
