# Generated by Django 3.2.8 on 2023-10-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0107_auto_20231027_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='identifier',
        ),
    ]
