# Generated by Django 3.2.8 on 2023-10-27 19:58

from django.db import migrations, models
import project_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0108_remove_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=project_management.models.generate_random_string, max_length=50),
        ),
    ]
