# Generated by Django 3.2.8 on 2023-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0109_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
