# Generated by Django 3.2.8 on 2024-02-29 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0118_alter_dailyprojectupdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableDailyUpdateNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enableproject', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_enabledailyupdatenow_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Project Update Enable by Me',
                'permissions': (('can_change_daily_update_last_time', 'Can change daily Update Last Time'),),
            },
        ),
    ]
