# Generated by Django 3.2.8 on 2024-02-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0119_enabledailyupdatenow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enabledailyupdatenow',
            options={'permissions': (('can_change_daily_update_any_time', 'Can change daily Update any Time'),), 'verbose_name': 'Project Update Enable', 'verbose_name_plural': 'Project Update Enable by me'},
        ),
    ]
