# Generated by Django 3.2.8 on 2024-07-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0150_auto_20240611_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByClient',
            fields=[
            ],
            options={
                'verbose_name': 'Group By Client',
                'verbose_name_plural': 'Group By Client',
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
        # migrations.RenameField(
        #     model_name='client',
        #     old_name='show_in_web',
        #     new_name='is_hour_breakdown',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='emergency_operation',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='is_highlight',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='on_boarded_by',
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='bill_from',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to='client_images', verbose_name='Client Image'),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='linkedin_url',
        #     field=models.URLField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='notes',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='is_highlighted',
        #     field=models.BooleanField(default=False, verbose_name='Is Highlighted?'),
        # ),
        # migrations.AlterField(
        #     model_name='client',
        #     name='email',
        #     field=models.EmailField(blank=True, max_length=80, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='client',
        #     name='logo',
        #     field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Company Logo'),
        # ),
        # migrations.CreateModel(
        #     name='ClientInvoiceDate',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('invoice_date', models.DateField(blank=True, null=True)),
        #         ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.client')),
        #     ],
        # ),
    ]
