# Generated by Django 3.2.8 on 2024-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0151_auto_20240613_1133'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='emergency_operation',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='is_highlight',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='on_boarded_by',
        # ),
        migrations.AddField(
            model_name='project',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Is Highlighted?'),
        ),
    ]
