# Generated by Django 3.2.8 on 2024-06-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0152_auto_20240613_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='show_in_web',
        ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='emergency_operation',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='is_highlight',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='on_boarded_by',
        # ),
    ]
