# Generated by Django 3.2.8 on 2024-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0155_auto_20240626_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emergency_operation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_highlight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='on_boarded_by',
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
