# Generated by Django 3.2.8 on 2024-06-27 22:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0157_auto_20240627_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bill_from',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
