# Generated by Django 3.2.8 on 2024-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0158_auto_20240627_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bill_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
