# Generated by Django 3.2.8 on 2024-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0159_alter_client_bill_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_hour_breakdown',
            field=models.BooleanField(default=False),
        ),
    ]
