# Generated by Django 3.2.8 on 2024-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0160_client_is_hour_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
