# Generated by Django 3.2.8 on 2024-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0161_client_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_item_description',
            field=models.TextField(blank=True, help_text='user for invoice template', null=True, verbose_name='Custom Item & Description'),
        ),
    ]
