# Generated by Django 3.2.8 on 2024-07-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0162_project_custom_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='custom_item_description',
        ),
        migrations.CreateModel(
            name='ClientInvoiceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.client')),
            ],
        ),
    ]
