# Generated by Django 3.2.8 on 2024-07-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0163_auto_20240701_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByClient',
            fields=[
            ],
            options={
                'verbose_name': 'Group By Client',
                'verbose_name_plural': 'Group By Client',
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
    ]
