# Generated by Django 3.2.8 on 2024-07-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0164_dailyprojectupdategroupbyclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyclient',
            options={'permissions': [('see_group_by_client', 'Can see group by client')], 'verbose_name': 'Group By Client', 'verbose_name_plural': 'Group By Client'},
        ),
    ]
