# Generated by Django 3.2.8 on 2024-07-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0165_alter_dailyprojectupdategroupbyclient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyclient',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'Group By Client', 'verbose_name_plural': 'Group By Client'},
        ),
    ]
