# Generated by Django 3.2.8 on 2024-07-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0167_auto_20240710_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='project_management.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='client',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='clients', to='project_management.ClientReview', verbose_name='Client Review'),
        ),
    ]
