# Generated by Django 3.2.8 on 2024-07-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0169_merge_0151_auto_20240709_1745_0168_auto_20240710_1809'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='client',
        #     name='payment_method',
        # ),
        # migrations.RemoveField(
        #     model_name='client',
        #     name='review',
        # ),
        # migrations.DeleteModel(
        #     name='ClientReview',
        # ),
        # migrations.DeleteModel(
        #     name='PaymentMethod',
        # ),
    ]
