# Generated by Django 3.2.8 on 2024-07-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0171_auto_20240710_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
    ]
