# Generated by Django 3.2.8 on 2024-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0173_auto_20240712_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Web Title'),
        ),
    ]
