# Generated by Django 3.2.8 on 2024-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0174_project_web_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='web_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Web Name'),
        ),
    ]
