# Generated by Django 3.2.8 on 2024-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0175_client_web_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='web_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Title'),
        ),
    ]
