# Generated by Django 3.2.8 on 2024-07-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0265_auto_20240715_1828'),
        ('project_management', '0177_auto_20240725_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprojecthour',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True, 'project_eligibility': True}, on_delete=django.db.models.deletion.RESTRICT, to='employee.employee'),
        ),
    ]
