# Generated by Django 3.2.8 on 2024-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0178_alter_employeeprojecthour_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprojecthour',
            name='update_data',
            field=models.TextField(blank=True, null=True, verbose_name='Update'),
        ),
    ]
