# Generated by Django 3.2.8 on 2024-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0179_employeeprojecthour_update_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails'),
        ),
    ]
