# Generated by Django 3.2.8 on 2024-08-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0181_client_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprojecthour',
            name='update_data',
        ),
    ]
