# Generated by Django 3.2.8 on 2024-08-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0267_alter_employeeattendance_options'),
        ('project_management', '0182_remove_employeeprojecthour_update_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthour',
            name='approved_by_cto',
        ),
        migrations.RemoveField(
            model_name='projecthour',
            name='client_exp_feedback',
        ),
        migrations.RemoveField(
            model_name='projecthour',
            name='operation_feedback',
        ),
        migrations.AddField(
            model_name='projecthour',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=20, verbose_name='TPM Approval Status'),
        ),
        migrations.AddField(
            model_name='projecthour',
            name='tpm',
            field=models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours', to='employee.employee'),
        ),
    ]
