# Generated by Django 3.2.8 on 2024-08-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0267_alter_employeeattendance_options'),
        ('project_management', '0183_auto_20240807_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='tpm',
            field=models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours', to='employee.employee', verbose_name='TPM'),
        ),
    ]
