# Generated by Django 3.2.8 on 2024-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0184_alter_projecthour_tpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='special_image',
            field=models.ImageField(blank=True, null=True, upload_to='special_image'),
        ),
    ]
