# Generated by Django 3.2.8 on 2024-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0186_projectkeypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
