# Generated by Django 3.2.8 on 2024-08-15 13:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0187_project_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_feedback',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
