# Generated by Django 3.2.8 on 2024-08-19 17:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0189_auto_20240819_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectServiceSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', tinymce.models.HTMLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_solutions', to='project_management.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
