# Generated by Django 3.2.8 on 2024-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0190_projectservicesolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedback',
            name='rating_billing',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='rating_long_term_interest',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='rating_output',
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating_overall_satisfaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating_quality_of_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating_recommendations',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating_understanding_of_requirements',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating_value_for_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='rating_communication',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='rating_time_management',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
