# Generated by Django 3.2.8 on 2024-08-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0191_auto_20240829_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='feedback_week',
            new_name='feedback_month',
        ),
    ]
