# Generated by Django 3.2.8 on 2024-09-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0192_rename_feedback_week_clientfeedback_feedback_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images', verbose_name='Client Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_web_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Web Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner Image'),
        ),
    ]
