# Generated by Django 3.2.8 on 2024-09-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0134_allprojectsbanner'),
        ('project_management', '0193_auto_20240909_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industries',
        ),
        migrations.AddField(
            model_name='project',
            name='industries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.industryserve'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.servicepage'),
        ),
        migrations.AlterField(
            model_name='projectkeyfeature',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image'),
        ),
    ]
