# Generated by Django 3.2.8 on 2024-09-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0194_auto_20240909_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industry_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_results',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_we_provide_image',
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
