# Generated by Django 3.2.8 on 2024-09-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0195_auto_20240909_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectResult',
            new_name='ProjectResultStatistic',
        ),
        migrations.AlterModelOptions(
            name='projectresultstatistic',
            options={'verbose_name': 'Project Result', 'verbose_name_plural': 'Project Results'},
        ),
    ]
