# Generated by Django 3.2.8 on 2024-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0196_auto_20240909_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkeyfeature',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/key_features/', verbose_name='Image'),
        ),
    ]
