# Generated by Django 3.2.8 on 2024-09-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0199_rename_number_projectresultstatistic_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresultstatistic',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_results', to='project_management.project'),
        ),
    ]
