# Generated by Django 3.2.8 on 2024-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0200_alter_projectresultstatistic_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images', verbose_name='Client Web Image'),
        ),
    ]
