# Generated by Django 3.2.8 on 2024-09-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0134_allprojectsbanner'),
        ('project_management', '0201_alter_project_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.industryweserve'),
        ),
    ]
