# Generated by Django 3.2.8 on 2024-09-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0202_alter_project_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industries',
        ),
    ]
