# Generated by Django 3.2.8 on 2024-09-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0204_project_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
    ]
