# Generated by Django 3.2.8 on 2024-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0205_remove_project_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
