# Generated by Django 3.2.8 on 2024-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0208_project_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkeyfeature',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
