# Generated by Django 3.2.8 on 2024-09-12 18:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0209_alter_projectkeyfeature_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedbackEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
    ]
