# Generated by Django 3.2.8 on 2024-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0209_alter_projectkeyfeature_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='project/display_image'),
        ),
    ]
