# Generated by Django 3.2.8 on 2024-09-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0210_clientfeedbackemail'),
        ('project_management', '0210_project_display_image'),
    ]

    operations = [
    ]
