# Generated by Django 3.2.8 on 2024-09-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0211_merge_20240912_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdate',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update'), ('can_approve_or_edit_daily_update_at_any_time', 'Can approve or update daily project update at any time'), ('can_submit_previous_daily_project_update', 'Can Submit Previous Daily Project Update')], 'verbose_name': 'Daily Project Update', 'verbose_name_plural': 'Daily Project Updates'},
        ),
    ]
