# Generated by Django 3.2.8 on 2024-09-13 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0212_alter_dailyprojectupdate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
