# Generated by Django 3.2.8 on 2024-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0213_alter_dailyprojectupdate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_need_feedback',
            field=models.BooleanField(default=False, verbose_name='Is Need Feedback'),
        ),
    ]
