# Generated by Django 3.2.8 on 2024-09-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0214_client_is_need_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedbackemail',
            name='feedback_type',
            field=models.CharField(choices=[('initial', 'Initial Feedback'), ('reminder', 'Reminder Feedback')], default='initial', max_length=50),
        ),
    ]
