# Generated by Django 3.2.8 on 2024-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0215_clientfeedbackemail_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_need_feedback',
            field=models.BooleanField(default=False, verbose_name='Need Feedback'),
        ),
    ]
