# Generated by Django 3.2.8 on 2024-10-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0216_alter_client_is_need_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHourHistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_history', models.FloatField(blank=True, null=True)),
                ('project_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projecthour')),
            ],
        ),
    ]
