# Generated by Django 3.2.8 on 2024-10-29 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0217_projecthourhistry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecthourhistry',
            old_name='project_hour',
            new_name='history',
        ),
        migrations.AddField(
            model_name='projecthourhistry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
