# Generated by Django 3.2.8 on 2024-11-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0218_auto_20241029_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectupdate',
            name='management_updates',
            field=models.TextField(blank=True, null=True, verbose_name='Updates For Management'),
        ),
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='updates_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Updates For Client'),
        ),
    ]
