# Generated by Django 3.2.8 on 2024-11-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0219_auto_20241104_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='management_updates',
            field=models.TextField(blank=True, null=True, verbose_name='Update For Management'),
        ),
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='updates_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Update For Client'),
        ),
    ]
