# Generated by Django 3.2.8 on 2024-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0221_clientattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='management_updates',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
