# Generated by Django 3.2.8 on 2024-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0222_alter_dailyprojectupdate_management_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='management_updates',
            field=models.TextField(blank=True, help_text='You can add any additional links or notes that help the DevLead/TPM understand your daily update', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='update',
            field=models.TextField(blank=True, default=' ', help_text='This will go to the client, so please ensure no unnecessary information is included', null=True),
        ),
    ]
