# Generated by Django 3.2.8 on 2024-11-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0223_auto_20241111_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_form',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
