# Generated by Django 3.2.8 on 2024-11-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0224_auto_20241114_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='active_form',
            new_name='active_from',
        ),
    ]
