# Generated by Django 3.2.8 on 2024-11-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0225_rename_active_form_client_active_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
