# Generated by Django 3.2.8 on 2024-11-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0226_alter_client_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.invoicetype'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='project_management.paymentmethod'),
        ),
    ]
