# Generated by Django 3.2.8 on 2024-11-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0227_auto_20241128_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bill_from',
            new_name='invoice_cc_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cc_email',
        ),
    ]
