# Generated by Django 3.2.8 on 2024-11-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0228_auto_20241128_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='invoice_cc_email',
        ),
    ]
