# Generated by Django 3.2.8 on 2024-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0229_remove_client_invoice_cc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_cc_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
