# Generated by Django 3.2.8 on 2024-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0230_client_invoice_cc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoice_cc_email',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for CC', null=True),
        ),
    ]
