# Generated by Django 3.2.8 on 2024-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0231_alter_client_invoice_cc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bill_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
