# Generated by Django 3.2.8 on 2024-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0233_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Follow Up', 'Follow Up'), ('Meeting', 'Meeting')], max_length=20, null=True),
        ),
    ]
