# Generated by Django 3.2.8 on 2024-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0234_auto_20241223_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Follow Up'), (2, 'Meeting')], null=True),
        ),
    ]
