# Generated by Django 3.2.8 on 2024-12-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0235_alter_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExperience',
            fields=[
            ],
            options={
                'verbose_name': 'CX',
                'verbose_name_plural': 'CX',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.client',),
        ),
    ]
