# Generated by Django 3.2.8 on 2025-01-10 11:59

import django.core.validators
from django.db import migrations, models
import project_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0236_clientexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprojecthour',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Document'),
        ),
    ]
