# Generated by Django 3.2.8 on 2025-01-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0236_clientexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='project_hours/'),
        ),
    ]
