# Generated by Django 3.2.8 on 2025-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0237_employeeprojecthour_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprojecthour',
            name='pdf_file',
        ),
    ]
