# Generated by Django 3.2.8 on 2025-01-10 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0237_projecthour_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='project_hours/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
