# Generated by Django 3.2.8 on 2025-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0238_remove_employeeprojecthour_pdf_file'),
        ('project_management', '0239_alter_projecthour_report_file'),
    ]

    operations = [
    ]
