# Generated by Django 3.2.8 on 2025-01-10 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0241_alter_projecthour_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='report_file',
            field=models.FileField(help_text='Must Be You have to Give Report File', null=True, upload_to='project_hours/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Weekly Update (PDF)'),
        ),
    ]
