# Generated by Django 3.2.8 on 2025-01-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0240_merge_20250110_1517'),
        ('project_management', '0242_alter_projecthour_report_file'),
    ]

    operations = [
    ]
