# Generated by Django 3.2.8 on 2025-01-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0243_merge_20250110_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(blank=True, help_text='Example: US Dollar, Euro, etc.', max_length=200, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='Example: USD, EUR, etc.', max_length=10, null=True)),
                ('icon', models.CharField(help_text='Currency symbol like $, €, £', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Set as active currency')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate relative to base currency', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Currency Type',
                'verbose_name_plural': 'Currency Types',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='project_management.currencytype'),
        ),
    ]
