# Generated by Django 3.2.8 on 2025-01-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0243_merge_20250110_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': [('can_see_all_project_field', 'Can See All Project Field'), ('can_see_hourly_rate', 'Can See Hourly Rate')]},
        ),
    ]
