# Generated by Django 3.2.8 on 2025-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0244_alter_project_options'),
        ('project_management', '0244_auto_20250124_1523'),
    ]

    operations = [
    ]
