# Generated by Django 3.2.8 on 2025-04-08 16:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0245_merge_20250124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontent',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
