# Generated by Django 3.2.8 on 2025-04-09 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0246_auto_20250408_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study_pdf',
            field=models.FileField(blank=True, help_text='Only Upload PDF File', null=True, upload_to='case_study_pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed. Please upload a valid PDF file.')], verbose_name='Case Study File (PDF)'),
        ),
    ]
