# Generated by Django 3.2.8 on 2025-04-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0247_project_case_study_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='case_study_pdf',
        ),
    ]
