# Generated by Django 3.2.8 on 2025-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0248_remove_project_case_study_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
