# Generated by Django 3.2.8 on 2025-04-15 19:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0249_projectcontent_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='iframe',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
