# Generated by Django 3.2.8 on 2025-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0250_projectcontent_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
