# Generated by Django 3.2.8 on 2025-04-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0251_client_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontent',
            options={'ordering': ['id']},
        ),
    ]
