# Generated by Django 3.2.8 on 2025-07-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0253_client_refered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='refered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.client'),
        ),
    ]
