# Generated by Django 3.2.8 on 2025-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0254_alter_client_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inactive_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
