# Generated by Django 3.2.8 on 2025-07-04 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0255_client_inactive_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
