# Generated by Django 3.2.8 on 2025-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0256_client_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='duration',
        ),
    ]
