# Generated by Django 3.2.8 on 2025-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0321_alter_employeerating_month'),
        ('project_management', '0257_remove_client_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('employees', models.ManyToManyField(blank=True, limit_choices_to={'active': True, 'project_eligibility': True}, related_name='teams', to='employee.Employee')),
                ('projects', models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='teams', to='project_management.Project')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
            },
        ),
    ]
