# Generated by Django 3.2.8 on 2025-07-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0257_remove_client_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('exclude_hourly_rate', 'Client hourly rate exclude.'), ('exclude_income', 'Client income exclude.')]},
        ),
    ]
