# Generated by Django 3.2.8 on 2025-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0258_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Upload team image', null=True, upload_to='team_images/'),
        ),
    ]
