# Generated by Django 3.2.8 on 2025-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0262_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('exclude_hourly_rate', 'Client hourly rate exclude.'), ('exclude_income', 'Client income exclude.'), ('can_mark_as_inactive', 'Can mark clients as inactive'), ('can_export_to_excel', 'Can export clients to Excel')]},
        ),
    ]
