# Generated by Django 3.2.8 on 2025-07-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0259_auto_20250709_1238'),
        ('project_management', '0263_alter_client_options'),
    ]

    operations = [
    ]
