# Generated by Django 3.2.8 on 2025-07-25 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0264_merge_20250723_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='report_file',
            field=models.FileField(blank=True, help_text='Please Submit the Report File', null=True, upload_to='project_hours/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Weekly Update (PDF)'),
        ),
    ]
