# Generated by Django 3.2.8 on 2025-08-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0265_alter_projecthour_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
    ]
