# Generated by Django 3.2.8 on 2025-08-13 19:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0197_auto_20250813_1932'),
        ('project_management', '0265_alter_projecthour_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='technology_type', chained_model_field='type', to='website.Technology', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.servecategory'),
        ),
    ]
