# Generated by Django 3.2.8 on 2025-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0197_auto_20250813_1932'),
        ('project_management', '0266_auto_20250814_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories_tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.Category', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.ServeCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': True}, related_name='projects', to='website.ServicePage', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.Technology', verbose_name='Technologies'),
        ),
    ]
