# Generated by Django 3.2.8 on 2025-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0197_auto_20250813_1932'),
        ('project_management', '0266_auto_20250813_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industries',
        ),
        migrations.AddField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.ServeCategory'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.ServicePage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.Technology', verbose_name='Technologies'),
        ),
    ]
