# Generated by Django 3.2.8 on 2025-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0217_technologyourprocess_technologywhychooseuscards_technologywhychooseuscardsdetails'),
        ('project_management', '0267_auto_20250814_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('exclude_hourly_rate', 'Client hourly rate exclude.'), ('exclude_income', 'Client income exclude.'), ('can_mark_as_inactive', 'Can mark clients as inactive'), ('can_export_to_excel', 'Can export clients to Excel'), ('can_export_to_pdf', 'Can export clients to PDF')]},
        ),
        migrations.AddField(
            model_name='client',
            name='decision_maker',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('mm', 'Marketing Manager')], default='ceo', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='issue',
            field=models.TextField(blank=True, help_text='Describe the issue or problem faced by the client', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_follow_up_date',
            field=models.DateField(blank=True, help_text='Next follow-up date for the client', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_potential',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'May Be')], default='maybe', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='upsell_opportunity',
            field=models.ManyToManyField(blank=True, related_name='upsell_opportunities', to='website.ServicePage', verbose_name='Upsell Opportunities'),
        ),
    ]
