# Generated by Django 3.2.8 on 2025-08-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0197_auto_20250813_1932'),
        ('project_management', '0267_auto_20250813_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.Category', verbose_name='tags'),
        ),
    ]
