# Generated by Django 3.2.8 on 2025-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0268_auto_20250819_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='issue',
        ),
        migrations.AlterField(
            model_name='client',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Issues / Concerns Raised'),
        ),
    ]
