# Generated by Django 3.2.8 on 2025-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0197_auto_20250813_1932'),
        ('project_management', '0269_alter_project_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': True}, related_name='projects', to='website.ServicePage', verbose_name='Services'),
        ),
    ]
