# Generated by Django 3.2.8 on 2025-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0269_auto_20250819_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
