# Generated by Django 3.2.8 on 2025-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0270_alter_client_client_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='decision_maker',
        ),
        migrations.AddField(
            model_name='client',
            name='client_value',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
