# Generated by Django 3.2.8 on 2025-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0272_auto_20250820_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Closing Summary/Future Scope'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Billing Notes'),
        ),
    ]
