# Generated by Django 3.2.8 on 2025-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0273_auto_20250821_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exclude_client_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Billing Address'),
        ),
    ]
