# Generated by Django 3.2.8 on 2025-09-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0275_alter_projecthour_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Estimation Activate Date')),
                ('estimation', models.FileField(upload_to='uploads/project_estimation/%y/%m')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Estimate Hours')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_projectestimation_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_estimations', to='project_management.project')),
            ],
            options={
                'verbose_name': 'Project Estimation',
                'verbose_name_plural': 'Project Estimations',
            },
        ),
    ]
