# Generated by Django 3.2.8 on 2025-09-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0276_projectestimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='behance_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
