# Generated by Django 3.2.8 on 2025-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0277_project_behance_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Designation'),
        ),
    ]
