# Generated by Django 3.2.8 on 2025-09-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0278_project_client_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField(blank=True, help_text='Date when this hourly rate became effective', null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate at this point in time', max_digits=10)),
                ('end_date', models.DateField(blank=True, help_text='Date when this hourly rate was replaced (NULL = current rate)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rate_history', to='project_management.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Hourly Rate History',
                'verbose_name_plural': 'Client Hourly Rate Histories',
                'ordering': ['-starting_date'],
            },
        ),
    ]
