# Generated by Django 3.2.8 on 2025-10-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0279_clienthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('exclude_hourly_rate', 'Client hourly rate exclude.'), ('exclude_income', 'Client income exclude.'), ('can_mark_as_inactive', 'Can mark clients as inactive'), ('can_export_to_excel', 'Can export clients to Excel'), ('can_export_to_pdf', 'Can export clients to PDF'), ('can_see_all_field', 'Can See All Field')]},
        ),
    ]
