# Generated by Django 3.2.8 on 2025-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0308_archivepagebody'),
        ('project_management', '0280_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='child_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': False}, related_name='child_projects', to='website.ServicePage', verbose_name='Child Services'),
        ),
    ]
