# Generated by Django 3.2.8 on 2025-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0281_project_child_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study_pdf',
            field=models.FileField(blank=True, help_text='Only Upload PDF File', null=True, upload_to='case_study_pdf'),
        ),
    ]
