# Generated by Django 3.2.8 on 2025-10-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0282_project_case_study_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdate',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update'), ('can_approve_or_edit_daily_update_at_any_time', 'Can approve or update daily project update at any time'), ('can_submit_previous_daily_project_update', 'Can Submit Previous Daily Project Update'), ('can_filter_daily_project_update_by_client', 'Can filter daily project update by client')], 'verbose_name': 'Daily Project Update', 'verbose_name_plural': 'Daily Project Updates'},
        ),
    ]
