# Generated by Django 3.2.8 on 2025-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0283_alter_dailyprojectupdate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='case_study_pdf',
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_pdf_link',
            field=models.URLField(blank=True, null=True, verbose_name='Case Study PDF Link'),
        ),
    ]
