# Generated by Django 3.2.8 on 2025-11-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0284_auto_20251103_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_video',
            field=models.URLField(blank=True, help_text='Short video for mediusware.com case study page', null=True),
        ),
    ]
