# Generated by Django 3.2.8 on 2025-11-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0285_project_short_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('client', models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='N/A', max_length=10)),
                ('tpm', models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='N/A', max_length=10)),
                ('ba', models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='N/A', max_length=10)),
                ('lead', models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='N/A', max_length=10)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_projectscommunication_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_priorities', to='project_management.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
