# Generated by Django 3.2.8 on 2025-11-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0286_projectscommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprojecthour',
            name='daily_update_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.dailyprojectupdate'),
        ),
    ]
