# Generated by Django 3.2.8 on 2025-12-08 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0287_employeeprojecthour_daily_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='end_date',
            field=models.DateField(blank=True, help_text='Estimation End Date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Estimation Activate Date', verbose_name='Start Date'),
        ),
    ]
