# Generated by Django 3.2.8 on 2025-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0288_auto_20251208_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscommunication',
            name='design_lead',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='N/A', max_length=10),
        ),
    ]
