# Generated by Django 3.2.8 on 2026-01-01 16:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0289_projectscommunication_design_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecutiveSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('section_title', models.CharField(max_length=255)),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', tinymce.models.HTMLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive_summaries', to='project_management.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
