# Generated by Django 3.2.8 on 2026-01-01 17:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0290_projectexecutivesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecutiveSummaryCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('executive_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_cards', to='project_management.projectexecutivesummary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
