# Generated by Django 3.2.8 on 2026-01-01 17:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0291_projectexecutivesummarycards'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexecutivesummarycards',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectexecutivesummary',
            name='section_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectexecutivesummary',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectexecutivesummarycards',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectexecutivesummarycards',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
