# Generated by Django 3.2 on 2021-06-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_auto_20210501_1936'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('total_value', models.FloatField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_salarysheet_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryToEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_salary', models.FloatField()),
                ('overtime', models.FloatField(null=True)),
                ('project_bonus', models.FloatField(null=True)),
                ('leave_bonus', models.FloatField(null=True)),
                ('gross_salary', models.FloatField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.employee')),
                ('salary_sheet_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
