# Generated by Django 3.2 on 2021-06-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210501_1936'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryToEmployee',
            new_name='EmployeeSalary',
        ),
    ]
