# Generated by Django 3.2 on 2021-06-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_salarytoemployee_employeesalary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeesalary',
            table='employee_salary',
        ),
    ]
