# Generated by Django 3.2 on 2021-06-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employeesalary_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeesalary',
            old_name='salary_sheet_it',
            new_name='salary_sheet',
        ),
    ]
