# Generated by Django 3.2 on 2021-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210609_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysheet',
            name='total_value',
            field=models.FloatField(blank=True),
        ),
    ]
