# Generated by Django 3.2 on 2021-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_salarysheet_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysheet',
            name='total_value',
            field=models.FloatField(null=True),
        ),
    ]
