# Generated by Django 3.2 on 2021-06-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_salarysheet_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarysheet',
            old_name='month',
            new_name='date',
        ),
    ]
