# Generated by Django 3.2.8 on 2024-02-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_merge_0115_auto_20240131_1740_0115_auto_20240131_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySheetTaxLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loan')),
                ('salarysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet')),
            ],
            options={
                'verbose_name': 'Salary Sheet Tax Loan',
                'verbose_name_plural': 'Salary Sheet Tax Loans',
            },
        ),
    ]
