# Generated by Django 3.2.8 on 2024-04-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0120_alter_expense_add_to_balance_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySheetTaxLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loan')),
                ('salarysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet')),
            ],
            options={
                'verbose_name': 'Salary Sheet Tax Loan',
                'verbose_name_plural': 'Salary Sheet Tax Loans',
            },
        ),
    ]
