# Generated by Django 3.2.8 on 2024-05-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_salarysheettaxloan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarysheet',
            options={'permissions': (('can_see_salary_on_salary_sheet', 'Can able to see Salary on Salary Sheet'),), 'verbose_name': 'Salary Sheet', 'verbose_name_plural': 'Salary Sheets'},
        ),
    ]
