# Generated by Django 3.2.8 on 2024-07-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_auto_20240513_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_send_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salarysheettaxloan',
            name='salarysheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet'),
        ),
    ]
