# Generated by Django 3.2.8 on 2024-05-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_auto_20240510_2052'),
        ('account', '0121_salarysheettaxloan'),
    ]

    operations = [
    ]
