# Generated by Django 3.2.8 on 2024-07-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0122_auto_20240709_1745'),
        ('account', '0122_auto_20240710_1809'),
    ]

    operations = [
    ]
