# Generated by Django 3.2.8 on 2024-05-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_salarysheettaxloan'),
        ('account', '0122_merge_0121_auto_20240510_2052_0121_salarysheettaxloan'),
    ]

    operations = [
    ]
