# Generated by Django 3.2.8 on 2024-05-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0123_merge_20240513_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysheettaxloan',
            name='salarysheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet'),
        ),
    ]

