# Generated by Django 3.2.8 on 2024-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0123_merge_0122_auto_20240709_1745_0122_auto_20240710_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypaymentvoucher',
            options={'verbose_name': 'Payment/Journal Voucher (Daily)', 'verbose_name_plural': 'Payment/Journal Vouchers (Daily)'},
        ),
    ]
