# Generated by Django 3.2.8 on 2024-08-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0272_tpmcomplain'),
        ('account', '0124_alter_dailypaymentvoucher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Investment Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_allowance', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentAllowanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='uploads/investment_allowance/')),
                ('investment_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.investmentallowance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
