# Generated by Django 3.2.8 on 2024-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0127_auto_20240813_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentallowance',
            options={'permissions': (('tax_information_approved', 'Can Approve Employee Tax Information'),)},
        ),
        migrations.AlterModelOptions(
            name='vehiclerebate',
            options={'permissions': (('tax_information_approved', 'Can Approve Employee Tax Information'),)},
        ),
        migrations.AlterField(
            model_name='vehiclerebate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vehicle Rebate Amount'),
        ),
    ]
