# Generated by Django 3.2.8 on 2024-08-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0128_auto_20240813_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentallowance',
            options={'permissions': (('tax_information_approved', 'Can Approve Employee Tax Documents'),)},
        ),
        migrations.AlterModelOptions(
            name='vehiclerebate',
            options={'permissions': (('tax_information_approved', 'Can Approve Employee Tax Documents'),)},
        ),
    ]
