# Generated by Django 3.2.8 on 2024-08-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0129_auto_20240813_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentallowance',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='vehiclerebate',
            name='approved',
        ),
    ]
