# Generated by Django 3.2.8 on 2024-08-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0274_auto_20240814_1339'),
        ('account', '0130_auto_20240813_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentallowance',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='investmentallowance', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='vehiclerebate',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vehiclerebate', to='employee.employee'),
        ),
    ]
