# Generated by Django 3.2.8 on 2024-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0131_auto_20240816_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('can_view_tax_loans', 'Can view tax loans')]},
        ),
        migrations.AddField(
            model_name='loan',
            name='tax_calan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
