# Generated by Django 3.2.8 on 2024-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0132_auto_20240917_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
