# Generated by Django 3.2.8 on 2024-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0133_salaryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEFTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originating_bank_routing_number', models.CharField(max_length=100)),
                ('originating_bank_account_number', models.CharField(max_length=100)),
                ('originating_bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('routing_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'BEFTN',
            },
        ),
    ]
