# Generated by Django 3.2.8 on 2024-11-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0134_beftn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryEmiLoan',
            fields=[
            ],
            options={
                'verbose_name': 'Monthly Salary EMI Loan',
                'verbose_name_plural': 'Monthly Salary EMI Loans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.employeesalary',),
        ),
    ]
