# Generated by Django 3.2.8 on 2024-11-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0135_salaryemiloan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'permissions': (('can_view_income_status', 'Can View Income Status'), ('can_view_income_total', 'Can View Income Total'))},
        ),
    ]
