# Generated by Django 3.2.8 on 2024-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0136_alter_income_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_send_invoice_email',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
    ]
