# Generated by Django 3.2.8 on 2024-12-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0137_income_is_send_invoice_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': (('can_approve_expense', 'Can Approve Expense'), ('can_view_all_expenses', 'Can View All Expenses'), ('can_add_balance_sheet', 'Can Add Balance Sheet'))},
        ),
    ]
