# Generated by Django 3.2.8 on 2024-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0138_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
