# Generated by Django 3.2.8 on 2025-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0139_loan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('hold', '✋ Hold'), ('approved', '✔ Approved')], default='pending', max_length=20),
        ),
    ]
