# Generated by Django 3.2.8 on 2025-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0140_alter_income_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
