# Generated by Django 3.2.8 on 2025-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0141_income_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Hours Description'),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Client Note'),
        ),
    ]
