# Generated by Django 3.2.8 on 2025-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0142_auto_20250522_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=20),
        ),
    ]
