# Generated by Django 3.2.8 on 2025-08-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0330_alter_excusenote_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0143_fund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_authorized',
            field=models.BooleanField(default=True, verbose_name='Is Authorized'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_by', to=settings.AUTH_USER_MODEL, verbose_name='Checked By'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Checked'),
        ),
        migrations.CreateModel(
            name='TDSChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Challan Date')),
                ('tds_type', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], default='group', max_length=10)),
                ('challan_no', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
