# Generated by Django 3.2.8 on 2025-08-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0330_alter_excusenote_status'),
        ('account', '0144_auto_20250815_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdschallan',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
