# Generated by Django 3.2.8 on 2025-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0330_alter_excusenote_status'),
        ('account', '0146_alter_tdschallan_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdschallan',
            name='employee',
        ),
        migrations.AddField(
            model_name='tdschallan',
            name='employee',
            field=models.ManyToManyField(blank=True, to='employee.Employee'),
        ),
    ]
