# Generated by Django 3.2.8 on 2025-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0147_auto_20250818_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdschallan',
            options={'verbose_name': 'TDS Challan', 'verbose_name_plural': 'TDS Challans'},
        ),
        migrations.AddField(
            model_name='tdschallan',
            name='tds_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0, help_text='Select the month for which TDS is applicable', max_length=20, verbose_name='TDS Month'),
        ),
    ]
