# Generated by Django 3.2.8 on 2025-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0148_auto_20250819_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdschallan',
            name='tds_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0, help_text='Select the month for which TDS is applicable', verbose_name='TDS Month'),
        ),
    ]
