# Generated by Django 3.2.8 on 2025-08-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0330_alter_excusenote_status'),
        ('account', '0149_alter_tdschallan_tds_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdschallan',
            name='individual_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_employee_tds_challan', to='employee.employee'),
        ),
    ]
