# Generated by Django 3.2.8 on 2025-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0150_tdschallan_individual_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdschallan',
            name='tds_type',
            field=models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], default='group', max_length=10, verbose_name='TDS Type'),
        ),
    ]
