# Generated by Django 3.2.8 on 2025-08-21 16:13

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_auto_20241128_1400'),
        ('account', '0151_alter_tdschallan_tds_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdschallan',
            name='tds_order',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdschallan',
            name='tds_year',
            field=models.ForeignKey(default=account.models.get_current_financial_year, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.financialyear'),
        ),
    ]
