# Generated by Django 3.2.8 on 2025-08-21 16:18

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_auto_20241128_1400'),
        ('account', '0152_auto_20250821_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdschallan',
            name='tds_year',
            field=models.ForeignKey(default=account.models.get_current_financial_year, help_text='Select the financial year for which TDS is applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.financialyear', verbose_name='TDS Year'),
        ),
    ]
