# Generated by Django 3.2.8 on 2025-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0153_alter_tdschallan_tds_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='boss_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
