# Generated by Django 3.2.8 on 2025-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0154_expense_boss_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='boss_comment',
        ),
        migrations.AddField(
            model_name='expanseattachment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expanseattachment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
