# Generated by Django 3.2.8 on 2025-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_inventoryitem_verification_code'),
        ('account', '0155_auto_20250828_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanseattachment',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='inventory_management.InventoryItem'),
        ),
        migrations.AddField(
            model_name='expanseattachment',
            name='inventory_ids',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
