# Generated by Django 3.2.8 on 2025-08-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0156_auto_20250828_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanseattachment',
            name='inventory_ids',
            field=models.CharField(help_text='Inventory Transaction verification ID', max_length=255, null=True),
        ),
    ]
