# Generated by Django 3.2.8 on 2025-08-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0157_alter_expanseattachment_inventory_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': (('can_approve_expense', 'Can Approve Expense'), ('can_view_all_expenses', 'Can View All Expenses'), ('can_add_balance_sheet', 'Can Add Balance Sheet'), ('can_see_note_field', 'Can See note field'))},
        ),
        migrations.AlterField(
            model_name='expanseattachment',
            name='inventory_ids',
            field=models.CharField(help_text='Inventory Transaction verification ID With Comma Separate Value', max_length=255, null=True),
        ),
    ]
