# Generated by Django 3.2.8 on 2025-08-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0158_auto_20250828_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expanseattachment',
            options={'permissions': (('can_update_expense_attachment', 'Can Update Expense Attachment'),)},
        ),
    ]
