# Generated by Django 3.2.8 on 2025-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0159_alter_expanseattachment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanseattachment',
            name='inventory_ids',
            field=models.CharField(blank=True, help_text='Inventory Transaction verification ID With Comma Separate Value', max_length=255, null=True),
        ),
    ]
