# Generated by Django 3.2.8 on 2025-09-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0160_alter_expanseattachment_inventory_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('view_fund_user', 'Can view fund user in admin')]},
        ),
    ]
