# Generated by Django 3.2.8 on 2025-09-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0161_alter_fund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('view_fund_user', 'Can view fund user in admin'), ('change_fund_user', 'Can change fund user in admin')]},
        ),
    ]
