# Generated by Django 3.2.8 on 2025-09-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0162_alter_fund_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFund',
            fields=[
                ('fund_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.fund')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.fund',),
        ),
    ]
