# Generated by Django 3.2.8 on 2025-09-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0164_alter_assistantfund_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssistantFund',
        ),
    ]
