# Generated by Django 3.2.8 on 2025-09-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0165_delete_assistantfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=20)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_assistantfund_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fund_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.fundcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_assistant_fund_user', 'Can view assistant fund user in admin'), ('change_assistant_fund_user', 'Can change assistant fund user in admin'), ('assistant_fund_superuser', 'Assistant fund superuser in admin')],
            },
        ),
    ]
