# Generated by Django 3.2.8 on 2025-09-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0166_assistantfund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantfund',
            options={'permissions': [('view_assistant_fund_user', 'Can view assistant fund user in admin'), ('change_assistant_fund_user', 'Can change assistant fund user in admin'), ('approve_assistant_fund_status', 'Can approve assistant fund status')]},
        ),
    ]
