# Generated by Django 3.2.8 on 2025-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0169_alter_assistantfund_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='add_to_balance_sheet',
            field=models.BooleanField(default=False, verbose_name='Reviewer'),
        ),
    ]
