# Generated by Django 3.2.8 on 2025-10-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0170_alter_expense_add_to_balance_sheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BEFTN',
        ),
    ]
