# Generated by Django 3.2.8 on 2024-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='loging_time',
            field=models.DateTimeField(),
        ),
    ]
