# Generated by Django 3.2.8 on 2024-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_userlogs_loging_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogs',
            options={'verbose_name': 'User Access Log'},
        ),
        migrations.AddField(
            model_name='userlogs',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
