# Generated by Django 3.2.8 on 2024-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20240902_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='browser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
