# Generated by Django 3.2.8 on 2024-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_userlogs_browser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
