# Generated by Django 3.2.8 on 2024-09-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20240903_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogs',
        ),
    ]
