# Generated by Django 3.2.8 on 2025-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_delete_userlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
