# Generated by Django 3.2.8 on 2024-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='agenda',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('meeting', 'Meeting')], max_length=20, null=True),
        ),
    ]
