# Generated by Django 3.2.8 on 2024-10-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20241015_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='agenda',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('meeting', 'Meeting'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
