# Generated by Django 3.2.8 on 2024-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_alter_reception_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10, null=True),
        ),
    ]
