# Generated by Django 3.2.8 on 2024-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_reception_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=10, null=True),
        ),
    ]
