# Generated by Django 3.2.8 on 2024-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_reception_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_url', models.CharField(max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
