# Generated by Django 3.2.8 on 2024-10-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_auto_20241017_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.agenda'),
        ),
    ]
