# Generated by Django 3.2.8 on 2024-10-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_reception_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='agenda',
            new_name='agenda_name',
        ),
    ]
