# Generated by Django 3.2.8 on 2024-10-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_rename_agenda_reception_agenda_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='agenda_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.agenda', verbose_name='Agenda'),
        ),
    ]
