# Generated by Django 3.2.8 on 2024-10-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_alter_reception_agenda_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
