# Generated by Django 3.2.8 on 2024-10-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_reception_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='agenda_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.agenda', verbose_name='Agenda'),
        ),
    ]
