# Generated by Django 3.2.8 on 2024-10-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_ceo_ceo_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CEO_Status',
            new_name='CEOStatus',
        ),
        migrations.AlterModelOptions(
            name='ceo',
            options={'verbose_name_plural': 'CEO'},
        ),
        migrations.AlterModelOptions(
            name='ceostatus',
            options={'verbose_name_plural': 'CEO Status'},
        ),
    ]
