# Generated by Django 3.2.8 on 2024-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_auto_20241029_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOCurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CEO Current Status',
            },
        ),
    ]
