# Generated by Django 3.2.8 on 2024-10-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0286_alter_employeerating_score'),
        ('reception', '0015_ceocurrentstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CEO',
            new_name='CEOWaitingList',
        ),
        migrations.AlterModelOptions(
            name='ceowaitinglist',
            options={'verbose_name_plural': 'CEO Waiting List'},
        ),
    ]
