# Generated by Django 3.2.8 on 2024-09-24 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3346649c-0d93-4b24-92b8-50a65019c044'), editable=False, primary_key=True, serialize=False),
        ),
    ]
