# Generated by Django 3.2.8 on 2024-09-24 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20240924_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.AddField(
            model_name='message',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49526a11-05a4-4398-ab90-ef85bf70efe6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
