# Generated by Django 3.2.8 on 2024-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_training_trainingoutline_trainingproject_trainingstructure_trainingstructuremodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
