# Generated by Django 3.2.8 on 2024-06-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_training_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='training_learning_topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='trainingstructure',
            old_name='title',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='training',
            name='short_description',
        ),
        migrations.AddField(
            model_name='trainingstructure',
            name='week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='TrainingStructureModule',
        ),
        migrations.AddField(
            model_name='traininglearningtopic',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.training'),
        ),
    ]
