# Generated by Django 3.2.8 on 2024-06-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20240613_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traininglearningtopic',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_learning_topic', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_outline', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingproject',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_project', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingstructure',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_structure', to='academy.training'),
        ),
    ]
