# Generated by Django 3.2.8 on 2024-06-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20240613_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglearningtopic',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_learning_topics', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_outlines', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingproject',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_projects', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingstructure',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_structures', to='academy.training'),
        ),
    ]
