# Generated by Django 3.2.8 on 2024-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20240613_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
