# Generated by Django 3.2.8 on 2024-06-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0154_auto_20240613_1921'),
        ('academy', '0007_auto_20240613_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='available_set',
        ),
        migrations.RemoveField(
            model_name='training',
            name='stack',
        ),
        migrations.CreateModel(
            name='TrainingTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('technology_name', models.ManyToManyField(to='project_management.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='training',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='academy.trainingtechnology'),
        ),
    ]
