# Generated by Django 3.2.8 on 2024-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20240613_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
