# Generated by Django 3.2.8 on 2024-06-13 22:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_training_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='training',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='trainingproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingproject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trainingproject',
            name='url',
        ),
        migrations.RemoveField(
            model_name='trainingstructure',
            name='day',
        ),
        migrations.RemoveField(
            model_name='trainingstructure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingstructure',
            name='training',
        ),
        migrations.CreateModel(
            name='TrainingStructureModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_structures', to='academy.training')),
                ('training_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.trainingstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
