# Generated by Django 3.2.8 on 2024-06-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_auto_20240613_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstructuremodule',
            name='training_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='academy.trainingstructure'),
        ),
    ]
