# Generated by Django 3.2.8 on 2024-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_trainingstructuremodule_training_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training'),
        ),
    ]
