# Generated by Django 3.2.8 on 2024-06-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_training_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='technology',
        ),
        migrations.AddField(
            model_name='trainingtechnology',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_technologies', to='academy.training'),
            preserve_default=False,
        ),
    ]
