# Generated by Django 3.2.8 on 2024-06-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_auto_20240614_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='student_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='traininglearningtopic',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_learning_topics', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_outlines', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingproject',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_projects', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingstructuremodule',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_structures', to='academy.training'),
        ),
        migrations.AlterField(
            model_name='trainingstructuremodule',
            name='training_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='academy.trainingstructure'),
        ),
        migrations.AlterField(
            model_name='trainingtechnology',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_technologies', to='academy.training'),
        ),
    ]
