# Generated by Django 3.2.8 on 2024-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_auto_20240614_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='training',
            field=models.ManyToManyField(blank=True, related_name='students', to='academy.Training'),
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(default='h.pdf', upload_to='student_files'),
            preserve_default=False,
        ),
    ]
