# Generated by Django 3.2.8 on 2024-06-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_auto_20240614_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingstructuremodule',
            name='day',
        ),
    ]
