# Generated by Django 3.2.8 on 2024-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_remove_trainingstructuremodule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_story')),
                ('description', models.TextField()),
                ('video', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
