# Generated by Django 3.2.8 on 2024-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_instructorfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWhyBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='why_best')),
            ],
            options={
                'verbose_name': 'Why We Are Best',
                'verbose_name_plural': 'Why We Are Best',
            },
        ),
    ]
