# Generated by Django 3.2.8 on 2024-06-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_homepagewhybest'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
