# Generated by Django 3.2.8 on 2024-06-27 20:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_training_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='trainingoutline',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingstructuremodule',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
