# Generated by Django 3.2.8 on 2024-06-28 11:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_auto_20240627_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
