# Generated by Django 3.2.8 on 2024-08-28 17:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0190_projectservicesolution'),
        ('academy', '0024_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='instructors/images/')),
                ('designation', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('short_description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='instructors/thumbnails/')),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video', models.URLField(blank=True, null=True)),
                ('course_overview_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('course_overview_image', models.ImageField(blank=True, null=True, upload_to='course_overviews/images/')),
                ('course_overview_description', tinymce.models.HTMLField()),
                ('training_reason_title', models.CharField(blank=True, max_length=255, null=True)),
                ('training_for_title', models.CharField(blank=True, max_length=255, null=True)),
                ('training_for_subtitle', models.TextField(blank=True, null=True)),
                ('training_outline_title', models.CharField(blank=True, max_length=255, null=True)),
                ('training_outline_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('training_tools_title', models.CharField(blank=True, max_length=255, null=True)),
                ('training_tools_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('project_showcase_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_showcase_description', models.TextField(blank=True, null=True)),
                ('student_review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('student_review_description', models.TextField(blank=True, null=True)),
                ('training_faq_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('instructors', models.ManyToManyField(related_name='training_programs', to='academy.Instructor')),
                ('training_technology', models.ManyToManyField(to='project_management.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_reasons/images/')),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reasons', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='training_for/images/')),
                ('prospect', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_for', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_faq', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Training_Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingoutline', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='studentreview/thumbnails/')),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='projectshowcase/thumbnails/')),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_showcase', to='academy.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trainingprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_project', to='academy.trainingprogram')),
            ],
        ),
    ]
