# Generated by Django 3.2.8 on 2024-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_instructor_practiceproject_projectshowcase_studentreview_training_outline_trainingfaq_trainingfor_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/images/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
