# Generated by Django 3.2.8 on 2024-08-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0026_auto_20240828_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceproject',
            name='trainingprogram',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='practice_projects',
            field=models.ManyToManyField(to='academy.PracticeProject'),
        ),
        migrations.CreateModel(
            name='FeatureHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feature_highlight/')),
                ('practice_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.practiceproject')),
            ],
        ),
    ]
