# Generated by Django 3.2.8 on 2024-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0027_auto_20240828_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
