# Generated by Django 3.2.8 on 2024-08-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_trainingprogram_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
