# Generated by Django 3.2.8 on 2024-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0029_alter_trainingprogram_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_image'),
        ),
    ]
