# Generated by Django 3.2.8 on 2024-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0030_trainingprogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practice_projects/'),
        ),
    ]
