# Generated by Django 3.2.8 on 2024-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0032_alltrainingbanner_homebanner_instructorbanner_pagebanner_successstorybanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
