# Generated by Django 3.2.8 on 2025-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='program_active_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivate', 'Deactivate'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
