# Generated by Django 3.1.7 on 2021-03-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.designation')),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.leave')),
                ('pay_scale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.payscale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
