# Generated by Django 3.2.8 on 2023-04-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_delete_employeefaqview'),
        ('employee', '0147_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFAQView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'FAQ List',
                'permissions': (('employee_faqs_view', 'Can Employee FAQ list view.'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.employeefaq',),
        ),
    ]
