# Generated by Django 3.2.8 on 2023-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0181_employeeneedhelp_needhelpposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeneedhelp',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
