# Generated by Django 3.2.8 on 2024-07-09 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0151_auto_20240709_1745'),
        ('employee', '0248_auto_20240607_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_tpm',
            field=models.BooleanField(default=False, help_text='Indicates if the employee is a Technical Project Manager (TPM)', verbose_name='TPM'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='project_name',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 15), '11:15 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(11, 45), '11:45 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(12, 45), '12:45 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 15), '1:15 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(13, 45), '1:45 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 15), '2:15 PM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(14, 45), '2:45 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 15), '3:15 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(15, 45), '3:45 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(16, 15), '4:15 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(16, 45), '4:45 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(17, 15), '5:15 PM'), (datetime.time(17, 30), '5:30 PM'), (datetime.time(17, 45), '5:45 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(18, 15), '6:15 PM'), (datetime.time(18, 30), '6:30 PM'), (datetime.time(18, 45), '6:45 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(19, 15), '7:15 PM'), (datetime.time(19, 30), '7:30 PM'), (datetime.time(19, 45), '7:45 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(20, 15), '8:15 PM'), (datetime.time(20, 45), '8:45 PM')]),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July')], default=7),
        ),
        migrations.CreateModel(
            name='LateAttendanceFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_late_attendance_fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'permissions': [('can_view_all_late_attendance', 'Can view all late attendance fines')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeUnderTPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': False}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee')),
                ('project', models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='project_management.project', verbose_name='Project')),
                ('tpm', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM')),
            ],
            options={
                'verbose_name': 'TPM',
                'verbose_name_plural': 'TPM',
            },
        ),
    ]
