# Generated by Django 3.2.8 on 2024-06-24 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0249_lateattendancefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateattendancefine',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
