# Generated by Django 3.2.8 on 2024-06-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0155_auto_20240626_1926'),
        ('employee', '0251_auto_20240626_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='project_name',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
