# Generated by Django 3.2.8 on 2024-07-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0252_alter_bookconferenceroom_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July')], default=7),
        ),
    ]
