# Generated by Django 3.2.8 on 2024-07-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0253_auto_20240705_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_tpm',
            field=models.BooleanField(default=False, help_text='Indicates if the employee is a Technical Project Manager (TPM)'),
        ),
        migrations.CreateModel(
            name='EmployeeUnderTPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee')),
                ('tpm', models.ForeignKey(limit_choices_to={'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Under TPM',
                'verbose_name_plural': 'Employee Under TPM',
            },
        ),
    ]
