# Generated by Django 3.2.8 on 2024-07-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0254_auto_20240708_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_tpm',
            new_name='TPM',
        ),
    ]
