# Generated by Django 3.2.8 on 2024-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0255_rename_is_tpm_employee_tpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='TPM',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_tpm',
            field=models.BooleanField(default=False, help_text='Indicates if the employee is a Technical Project Manager (TPM)', verbose_name='TPM'),
        ),
    ]
