# Generated by Django 3.2.8 on 2024-07-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0256_auto_20240708_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeundertpm',
            options={'verbose_name': 'TPM', 'verbose_name_plural': 'TPM'},
        ),
        migrations.AlterField(
            model_name='employeeundertpm',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeundertpm',
            name='tpm',
            field=models.ForeignKey(limit_choices_to={'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM'),
        ),
    ]
