# Generated by Django 3.2.8 on 2024-07-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0257_auto_20240708_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeundertpm',
            name='tpm',
            field=models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM'),
        ),
    ]
