# Generated by Django 3.2.8 on 2024-07-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0166_alter_dailyprojectupdategroupbyclient_options'),
        ('employee', '0258_alter_employeeundertpm_tpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_projects', to='project_management.project', verbose_name='Project')),
                ('tpm', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_projects', to='employee.employee', verbose_name='TPM')),
            ],
            options={
                'verbose_name': 'TPM Project',
                'verbose_name_plural': 'TPM Projects',
            },
        ),
    ]
