# Generated by Django 3.2.8 on 2024-07-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0166_alter_dailyprojectupdategroupbyclient_options'),
        ('employee', '0259_tpmproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tpmproject',
            name='tpm',
        ),
        migrations.AddField(
            model_name='employeeundertpm',
            name='project',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='project_management.project', verbose_name='Project'),
        ),
        migrations.AddConstraint(
            model_name='employeeundertpm',
            constraint=models.UniqueConstraint(fields=('employee', 'tpm'), name='unique_employee_under_tpm'),
        ),
        migrations.DeleteModel(
            name='TPMProject',
        ),
    ]
