# Generated by Django 3.2.8 on 2024-07-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0260_auto_20240709_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeundertpm',
            options={},
        ),
        migrations.AlterField(
            model_name='employeeundertpm',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': False}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee'),
        ),
    ]
