# Generated by Django 3.2.8 on 2024-07-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0261_auto_20240709_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeUnderTPM',
        ),
    ]
