# Generated by Django 3.2.8 on 2024-07-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0166_alter_dailyprojectupdategroupbyclient_options'),
        ('employee', '0262_delete_employeeundertpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUnderTPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': False}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee')),
                ('project', models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='project_management.project', verbose_name='Project')),
                ('tpm', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM')),
            ],
            options={
                'verbose_name': 'TPM',
                'verbose_name_plural': 'TPM',
            },
        ),
    ]
