# Generated by Django 3.2.8 on 2024-07-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0249_auto_20240709_1745'),
        ('employee', '0263_employeeundertpm'),
    ]

    operations = [
    ]
