# Generated by Django 3.2.8 on 2024-07-15 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0264_merge_0249_auto_20240709_1745_0263_employeeundertpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerating',
            name='adaptability_and_flexibility',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='communication_effectiveness',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='continuous_learning',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='feedback_responsiveness',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='innovation_and_creativity',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='leadership_potential',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='overall_contribution_to_team_success',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='problem_solving_ability',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='professional_growth_and_development',
        ),
        migrations.RemoveField(
            model_name='employeerating',
            name='project',
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='score',
            field=models.SmallIntegerField(default=0, help_text='Max Score Will be 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
