# Generated by Django 3.2.8 on 2024-08-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0266_alter_employeerating_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'permissions': (('can_see_full_month_attendance', 'Can see full month attendance'),), 'verbose_name': 'Employee Attendance', 'verbose_name_plural': 'Employee Attendances'},
        ),
    ]
