# Generated by Django 3.2.8 on 2024-08-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0267_alter_employeeattendance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMComplain',
            fields=[
                ('employeeundertpm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.employeeundertpm')),
                ('complain', models.TextField()),
                ('management_feedback', models.TextField()),
                ('status', models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=100, verbose_name='Complain Status')),
            ],
            bases=('employee.employeeundertpm',),
        ),
    ]
