# Generated by Django 3.2.8 on 2024-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0269_alter_tpmcomplain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmcomplain',
            name='complain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmcomplain',
            name='management_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
