# Generated by Django 3.2.8 on 2024-08-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0270_auto_20240812_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TPMComplain',
        ),
    ]
