# Generated by Django 3.2.8 on 2024-08-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0184_alter_projecthour_tpm'),
        ('employee', '0271_delete_tpmcomplain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(blank=True, null=True)),
                ('management_feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=100, verbose_name='Complain Status')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_tpm': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.employee')),
                ('project', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.project', verbose_name='Project')),
                ('tpm', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='TPM')),
            ],
            options={
                'verbose_name_plural': "TPM's Complain",
            },
        ),
    ]
