# Generated by Django 3.2.8 on 2024-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0272_tpmcomplain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmcomplain',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved'), ('observation', '🔍 Observation')], default='pending', max_length=100, verbose_name='Complain Status'),
        ),
    ]
