# Generated by Django 3.2.8 on 2024-08-14 13:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0273_alter_tpmcomplain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmcomplain',
            name='complain_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tpmcomplain',
            name='feedback_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tpmcomplain',
            name='complain',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmcomplain',
            name='management_feedback',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
