# Generated by Django 3.2.8 on 2024-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0274_auto_20240814_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September')], default=9),
        ),
    ]
