# Generated by Django 3.2.8 on 2024-09-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0278_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'), ('can_access_average_rating', 'Can access average rating of Employee.'), ('can_see_salary_history', 'Can able to see salary history.'), ('can_print_salary_certificate', 'Can print salary certificate'), ('can_print_salary_payslip', 'Can print salary payslip'), ('can_show_permanent_increment', 'Can show permanent increment'))},
        ),
    ]
