# Generated by Django 3.2.8 on 2024-09-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0279_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEFTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originating_bank_routing_number', models.CharField(max_length=100)),
                ('originating_bank_account_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beftn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employee.beftn'),
        ),
    ]
