# Generated by Django 3.2.8 on 2024-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0280_auto_20240925_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='beftn',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='routing_no',
        ),
        migrations.AddField(
            model_name='beftn',
            name='originating_bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beftn',
            name='routing_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
