# Generated by Django 3.2.8 on 2024-09-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0281_auto_20240926_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BEFTN',
        ),
    ]
