# Generated by Django 3.2.8 on 2024-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0283_alter_employeerating_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateattendancefine',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lateattendancefine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
