# Generated by Django 3.2.8 on 2024-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0284_auto_20241002_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerating',
            name='adaptability_and_flexibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='collaboration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='communication_effectiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='leadership_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='overall_contribution_to_team_success',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='problem_solving_ability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='professional_growth_and_development',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='rating_overall_satisfaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='rating_quality_of_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='rating_time_management',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='rating_understanding_of_requirements',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
