# Generated by Django 3.2.8 on 2024-10-24 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0285_auto_20241024_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='score',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Max Score Will be 25', null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
