# Generated by Django 3.2.8 on 2024-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0286_alter_employeerating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateattendancefine',
            name='is_consider',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
