# Generated by Django 3.2.8 on 2024-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0287_lateattendancefine_is_consider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateattendancefine',
            name='is_consider',
            field=models.BooleanField(default=False),
        ),
    ]
