# Generated by Django 3.2.8 on 2024-10-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0288_alter_lateattendancefine_is_consider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateattendancefine',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
