# Generated by Django 3.2.8 on 2024-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0289_alter_lateattendancefine_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateattendancefine',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
