# Generated by Django 3.2.8 on 2024-11-15 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0292_auto_20241106_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_lesshour_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='less_hour_employees', to='employee.employee')),
                ('tpm', models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, on_delete=django.db.models.deletion.CASCADE, related_name='less_hour_tpms', to='employee.employee', verbose_name='TPM')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
