# Generated by Django 3.2.8 on 2024-11-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0293_lesshour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesshour',
            name='tpm',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='less_hour_tpms', to='employee.employee', verbose_name='TPM'),
        ),
    ]
