# Generated by Django 3.2.8 on 2024-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0294_alter_lesshour_tpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesshour',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
