# Generated by Django 3.2.8 on 2024-11-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0295_lesshour_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': (('can_approve_leave_applications', 'Can able to approve leave applications'), ('can_add_leave_at_any_time', 'Can able to add leave at any time'), ('can_update_after_approve', 'Can able to update after approve'))},
        ),
    ]
