# Generated by Django 3.2.8 on 2024-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0296_alter_leave_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateattendancefine',
            name='is_consider',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lateattendancefine',
            name='total_late_attendance_fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Late Attendance Fine'),
        ),
    ]
