# Generated by Django 3.2.8 on 2024-11-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0297_auto_20241125_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'permissions': (('can_see_full_month_attendance', 'Can see full month attendance'), ('can_download_attendance_report', 'Can download attendance report')), 'verbose_name': 'Employee Attendance', 'verbose_name_plural': 'Employee Attendances'},
        ),
    ]
