# Generated by Django 3.2.8 on 2024-11-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0226_alter_client_hourly_rate'),
        ('employee', '0298_alter_employeeattendance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeundertpm',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='project_management.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='employeeundertpm',
            name='tpm',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM'),
        ),
    ]
