# Generated by Django 3.2.8 on 2024-11-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0299_auto_20241128_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeundertpm',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_tpm': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_under_tpm', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeundertpm',
            name='tpm',
            field=models.ForeignKey(limit_choices_to={'active': True, 'is_tpm': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_overseen', to='employee.employee', verbose_name='TPM'),
        ),
    ]
