# Generated by Django 3.2.8 on 2024-12-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0303_inbox_meetingsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
