# Generated by Django 3.2.8 on 2024-12-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0304_inbox_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'permissions': [('can_see_all_employee_inbox', 'Can able to see all employee inbox')]},
        ),
    ]
