# Generated by Django 3.2.8 on 2024-12-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0306_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.documentname', to_field='name'),
        ),
    ]
