# Generated by Django 3.2.8 on 2025-01-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0308_alter_attachment_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January')], default=1),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2025),
        ),
    ]
