# Generated by Django 3.2.8 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0309_auto_20250101_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February')], default=2),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025)], default=2025),
        ),
    ]
