# Generated by Django 3.2.8 on 2025-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0310_auto_20250204_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesshour',
            name='hr_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='HR Feedback'),
        ),
        migrations.AlterField(
            model_name='lesshour',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='TPM Feedback'),
        ),
    ]
