# Generated by Django 3.2.8 on 2025-02-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0311_auto_20250207_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesshour',
            options={'permissions': (('can_see_hr_feedback_field', 'Can see hr feedback field'),)},
        ),
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'permissions': (('can_see_note_field', 'Can see note field'),)},
        ),
    ]
