# Generated by Django 3.2.8 on 2025-02-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0312_auto_20250210_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceOne',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employeeattendance',),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceThree',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employeeattendance',),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceTwo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employeeattendance',),
        ),
    ]
