# Generated by Django 3.2.8 on 2025-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0313_employeeattendanceone_employeeattendancethree_employeeattendancetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exception_la',
            field=models.BooleanField(default=False),
        ),
    ]
