# Generated by Django 3.2.8 on 2025-03-07 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0314_employee_exception_la'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 15), '9:15 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(9, 45), '9:45 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 15), '10:15 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(10, 45), '10:45 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 15), '11:15 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(11, 45), '11:45 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(12, 45), '12:45 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 15), '1:15 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(13, 45), '1:45 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 15), '2:15 PM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(14, 45), '2:45 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 15), '3:15 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(15, 45), '3:45 PM')]),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March')], default=3),
        ),
    ]
