# Generated by Django 3.2.8 on 2025-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0315_auto_20250307_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAttendanceOne',
        ),
        migrations.DeleteModel(
            name='EmployeeAttendanceThree',
        ),
        migrations.DeleteModel(
            name='EmployeeAttendanceTwo',
        ),
    ]
