# Generated by Django 3.2.8 on 2025-04-08 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0317_alter_employeerating_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialEmployeeAttendance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employeeattendance',),
        ),
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 15), '11:15 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(11, 45), '11:45 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 15), '12:15 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(12, 45), '12:45 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 15), '1:15 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(13, 45), '1:45 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 15), '2:15 PM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(14, 45), '2:45 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 15), '3:15 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(15, 45), '3:45 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(16, 15), '4:15 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(16, 45), '4:45 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(17, 15), '5:15 PM'), (datetime.time(17, 30), '5:30 PM'), (datetime.time(17, 45), '5:45 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(18, 15), '6:15 PM'), (datetime.time(18, 30), '6:30 PM'), (datetime.time(18, 45), '6:45 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(19, 15), '7:15 PM'), (datetime.time(19, 30), '7:30 PM'), (datetime.time(19, 45), '7:45 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(20, 15), '8:15 PM'), (datetime.time(20, 45), '8:45 PM')]),
        ),
    ]
