# Generated by Django 3.2.8 on 2025-04-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0318_auto_20250408_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'permissions': (('can_see_note_field', 'Can see note field'), ('can_see_salary_receive_history', 'Can See Employee Salary Receive History'))},
        ),
    ]
