# Generated by Django 3.2.8 on 2025-05-22 13:56

from django.db import migrations, models
import employee.models.employee_rating_models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0319_alter_salaryhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May')], default=employee.models.employee_rating_models.get_current_month),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025)], default=employee.models.employee_rating_models.get_current_year),
        ),
    ]
