# Generated by Django 3.2.8 on 2025-07-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0321_alter_employeerating_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='excusenote',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Actions taken to resolve the incident', null=True),
        ),
        migrations.AddField(
            model_name='excusenote',
            name='incedent_date',
            field=models.DateField(blank=True, help_text='Date of the incident', null=True),
        ),
        migrations.AddField(
            model_name='excusenote',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_excuse_notes', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='excusenote',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Severity of the incident', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excusenote',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', help_text='Status of the excuse note', max_length=20, null=True),
        ),
    ]
