# Generated by Django 3.2.8 on 2025-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0323_auto_20250722_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excusenote',
            old_name='incedent_date',
            new_name='incident_date',
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_leave_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('non_paid', 'Non Paid Leave'), ('half_day', 'Half Day Casual'), ('half_day_medical', 'Half Day Medical'), ('half_day_non_paid', 'Half Day Non Paid'), ('emergency_leave', 'Emergency Leave'), ('system_generated', 'System Generated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('non_paid', 'Non Paid Leave'), ('half_day', 'Half Day Casual'), ('half_day_medical', 'Half Day Medical'), ('half_day_non_paid', 'Half Day Non Paid'), ('emergency_leave', 'Emergency Leave'), ('system_generated', 'System Generated')], max_length=20, verbose_name='Approved Leave Type'),
        ),
    ]
