# Generated by Django 3.2.8 on 2025-07-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0324_auto_20250725_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excusenote',
            old_name='incident_date',
            new_name='incedent_date',
        ),
    ]
