# Generated by Django 3.2.8 on 2025-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0325_rename_incident_date_excusenote_incedent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excusenote',
            name='incedent_date',
            field=models.DateField(blank=True, help_text='Date of the incident', null=True, verbose_name='incident_date'),
        ),
    ]
