# Generated by Django 3.2.8 on 2025-07-28 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0326_alter_excusenote_incedent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excusenote',
            name='incedent_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date of the incident', null=True, verbose_name='incident_date'),
        ),
    ]
