# Generated by Django 3.2.8 on 2025-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0327_alter_excusenote_incedent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateattendancefine',
            name='total_late_attendance_fine',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Late Attendance Fine'),
        ),
    ]
