# Generated by Django 3.2.8 on 2025-08-01 11:56

from django.db import migrations, models
import employee.models.employee_rating_models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0328_alter_lateattendancefine_total_late_attendance_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August')], default=employee.models.employee_rating_models.get_current_month),
        ),
    ]
