# Generated by Django 3.2.8 on 2025-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0329_alter_employeerating_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excusenote',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('note', 'Note')], default='pending', help_text='Status of the excuse note', max_length=20, null=True),
        ),
    ]
