# Generated by Django 3.2.8 on 2025-09-01 12:11

from django.db import migrations, models
import employee.models.employee_rating_models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0330_alter_excusenote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September')], default=employee.models.employee_rating_models.get_current_month),
        ),
    ]
