# Generated by Django 3.2.8 on 2025-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0331_alter_employeerating_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_pdfs/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_info',
            field=models.CharField(blank=True, help_text='i.e: 59530389237, Circle–138, Zone-11, Dhaka', max_length=255, null=True, verbose_name='TIN Number'),
        ),
    ]
