# Generated by Django 3.2.8 on 2025-09-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0332_auto_20250915_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_pdf',
        ),
    ]
