# Generated by Django 3.2.8 on 2025-09-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0334_socialmedia'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='employeesocial',
        #     name='title',
        # ),
        migrations.AddField(
            model_name='employeesocial',
            name='social_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.socialmedia'),
        ),
    ]
