# Generated by Django 3.2.8 on 2025-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0335_auto_20250916_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesocial',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
