# Generated by Django 3.2.8 on 2025-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0336_employeesocial_title'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='employeesocial',
        #     name='title',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
    ]
