# Generated by Django 3.2.8 on 2025-09-18 13:01

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_auto_20241128_1400'),
        ('employee', '0337_alter_employeesocial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tds_year',
            field=models.ForeignKey(blank=True, default=account.models.get_current_financial_year, help_text='Use for Tax Acknowledgement Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.financialyear', verbose_name='TDS Year'),
        ),
        # migrations.AlterField(
        #     model_name='employeesocial',
        #     name='title',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
    ]
