# Generated by Django 3.2.8 on 2025-09-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0338_auto_20250918_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxAcknowledgement',
            fields=[
            ],
            options={
                'verbose_name': 'Tax Acknowledgement',
                'verbose_name_plural': 'Tax Acknowledgements',
                'permissions': (('view_all_tax_acknowledgement', 'View All Tax Acknowledgement'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.attachment',),
        ),
    ]
