# Generated by Django 3.2.8 on 2025-09-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_auto_20241128_1400'),
        ('employee', '0339_auto_20250918_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='tds_year',
            field=models.ForeignKey(blank=True, help_text='Use for Tax Acknowledgement Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.financialyear', verbose_name='TDS Year'),
        ),
    ]
