# Generated by Django 3.2.8 on 2025-09-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0338_alter_employeesocial_title'),
        ('employee', '0340_auto_20250918_1802'),
    ]

    operations = [
    ]
