# Generated by Django 3.2.8 on 2025-09-22 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0341_merge_20250918_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformanceFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_skill', models.SmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text='Technical/Functional Skills rating (1-5). Weight: 40%. ')),
                ('project_deliver', models.SmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text='Project Deliverables rating (1-5). Weight: 30%. ')),
                ('client_feedback', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Peer/Client Feedback rating (1-5). Weight: 20%. ')),
                ('initiative_learning', models.SmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text='Initiative & Learning rating (1-5). Weight: 10%. ')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employeeperformancefeedback_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(help_text='The employee being evaluated for performance.', on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Feedback',
                'verbose_name_plural': 'Employee Feedbacks',
                'ordering': ('-created_at',),
            },
        ),
    ]
