# Generated by Django 3.2.8 on 2025-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0342_employeeperformancefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeperformancefeedback',
            name='client_feedback',
            field=models.SmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text='Peer/Client Feedback rating (1-5). Weight: 20%. '),
        ),
    ]
