# Generated by Django 3.2.8 on 2025-09-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0343_alter_employeeperformancefeedback_client_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeTaxAcknowledgement',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='tds_year',
        ),
    ]
