# Generated by Django 3.2.8 on 2025-09-24 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_auto_20241128_1400'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0344_auto_20250924_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='tax_acknowledgement/')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employeetaxacknowledgement_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('tds_year', models.ForeignKey(help_text='Use for Tax Acknowledgement Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.financialyear', verbose_name='TDS Year')),
            ],
            options={
                'verbose_name': 'Tax Acknowledgement',
                'verbose_name_plural': 'Tax Acknowledgements',
                'permissions': (('view_all_tax_acknowledgement', 'View All Tax Acknowledgement'),),
            },
        ),
    ]
