# Generated by Django 3.2.8 on 2025-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0347_employeeavailableslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailableslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
