# Generated by Django 3.2.8 on 2025-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0348_alter_employeeavailableslot_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailableslot',
            name='slot',
            field=models.CharField(choices=[('half', 'Half-time'), ('full', 'Full-time'), ('n/a', 'N/A')], max_length=255),
        ),
    ]
