# Generated by Django 3.2.8 on 2025-10-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0349_alter_employeeavailableslot_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'), ('can_access_average_rating', 'Can access average rating of Employee.'), ('can_see_salary_history', 'Can able to see salary history.'), ('can_print_salary_certificate', 'Can print salary certificate'), ('can_print_salary_payslip', 'Can print salary payslip'), ('can_show_permanent_increment', 'Can show permanent increment'), ('can_send_mail_to_employee', 'Can send mail to employee'), ('can_print_employee_info', 'Can print employee info'), ('eligible_for_home_page_reload', 'Eligible For Home Page Reload'))},
        ),
    ]
