# Generated by Django 3.2.8 on 2025-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0350_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateattendancefine',
            name='is_request_for_consider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lateattendancefine',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
