# Generated by Django 3.2.8 on 2025-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0351_auto_20251016_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformancefeedback',
            name='note',
            field=models.TextField(blank=True, help_text="Additional notes or comments about the employee's performance.", null=True),
        ),
    ]
