# Generated by Django 3.2.8 on 2025-10-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0351_auto_20251016_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateattendancefine',
            name='hr_feedback_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_feedback_given_employee', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='lateattendancefine',
            name='hr_note',
            field=models.TextField(blank=True, null=True, verbose_name='HR Remarks'),
        ),
        migrations.AlterField(
            model_name='lateattendancefine',
            name='is_request_for_consider',
            field=models.BooleanField(default=False, verbose_name='Request for Consideration'),
        ),
        migrations.AlterField(
            model_name='lateattendancefine',
            name='note',
            field=models.TextField(help_text='Reason for late.', null=True, verbose_name='Employee Remarks'),
        ),
    ]
