# Generated by Django 3.2.8 on 2025-10-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0352_auto_20251016_1921'),
        ('employee', '0352_employeeperformancefeedback_note'),
    ]

    operations = [
    ]
