# Generated by Django 3.2.8 on 2025-11-03 15:30

from django.db import migrations, models
import employee.models.employee_rating_models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0353_merge_20251017_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November')], default=employee.models.employee_rating_models.get_current_month),
        ),
    ]
