# Generated by Django 3.2.8 on 2025-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0354_alter_employeerating_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
