# Generated by Django 3.2.8 on 2025-12-05 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0356_alter_employeerating_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSnack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('number_of_snacks', models.PositiveSmallIntegerField(default=0, verbose_name='Number')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employeesnack_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnackNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_snacknote_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack_note_employee_snack', to='employee.employeesnack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
