# Generated by Django 3.2.8 on 2026-01-01 16:52

from django.db import migrations, models
import employee.models.employee_rating_models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0358_auto_20251225_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January')], default=employee.models.employee_rating_models.get_current_month),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025), (2026, 2026)], default=employee.models.employee_rating_models.get_current_year),
        ),
    ]
