# Generated by Django 3.2.8 on 2025-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
