# Generated by Django 3.2.8 on 2025-10-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0281_project_child_services'),
        ('news_letter', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_subscribed', models.BooleanField(blank=True, default=True)),
                ('project_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_subscribers', to='project_management.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
