# Generated by Django 3.2.8 on 2025-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0004_casestudysubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudysubscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
