# Generated by Django 3.2.8 on 2025-12-17 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0005_alter_casestudysubscriber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
