# Generated by Django 3.2.8 on 2024-12-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0302_alter_employeerating_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0023_alter_employeeasset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(help_text='Date of purchase')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_addition_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('depreciation', models.IntegerField(default=0, help_text='In %')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_assethead_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Head',
                'verbose_name_plural': 'Heads',
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_assetitem_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management.assethead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_assigned',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='need_repair',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='note',
        ),
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateField(help_text='Date of purchase', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employeeassignedasset',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='privileges',
            field=models.ManyToManyField(blank=True, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeassignedasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='asset_management.asset'),
        ),
        migrations.AlterField(
            model_name='employeeassignedasset',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assets', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='employee.employee'),
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.AddField(
            model_name='asset',
            name='addition',
            field=models.ManyToManyField(blank=True, null=True, related_name='asset_additions', to='asset_management.Addition'),
        ),
        migrations.AddField(
            model_name='asset',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.assethead'),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='head', chained_model_field='head', null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.assetitem'),
        ),
    ]
