# Generated by Django 3.2.8 on 2024-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0024_auto_20241204_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
