# Generated by Django 3.2.8 on 2024-12-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0026_auto_20241206_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
