# Generated by Django 3.2.8 on 2024-12-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0027_asset_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='title',
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_management.brand'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.assethead'),
        ),
    ]
