# Generated by Django 3.2.8 on 2024-12-06 14:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0028_auto_20241206_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_management.brand'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='head', chained_model_field='head', null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.assetitem', verbose_name='Category'),
        ),
    ]
