# Generated by Django 3.2.8 on 2024-12-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0031_auto_20241209_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='approved_at',
            field=models.DateField(editable=False, null=True),
        ),
    ]
