# Generated by Django 3.2.8 on 2025-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0032_assetrequest_approved_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=10),
        ),
    ]
