# Generated by Django 3.2.8 on 2025-01-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0033_auto_20250115_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('can_view_asset_status', 'Can view asset status'), ('can_change_asset_status', 'Can change asset status'), ('can_view_asset_history', 'Can view asset history')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
    ]
