# Generated by Django 3.2.8 on 2025-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0034_alter_asset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], db_index=True, default='pending', max_length=10),
        ),
    ]
