# Generated by Django 3.2.8 on 2025-09-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0035_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='HP, LG, Samsung, DELL, etc.', max_length=255, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_assetbrand_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Table, Chair, Monitor, Keyboard, Mouse, Headphone, RAM, SSD, HDD, GPU', max_length=255, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_assetcategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processor', models.CharField(blank=True, help_text='CPU details', max_length=100, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, help_text='RAM size in GB e.g., 16', null=True)),
                ('storage', models.PositiveIntegerField(blank=True, help_text='SSD/HDD size in GB e.g., 250', null=True)),
                ('display_size', models.PositiveIntegerField(blank=True, help_text='Screen size in inches e.g., 24', null=True)),
                ('gpu', models.CharField(blank=True, help_text='GPU model, if any', max_length=100, null=True)),
                ('other_specs', models.TextField(blank=True, help_text='Any additional configuration', null=True)),
                ('serial', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_duration', models.PositiveIntegerField(blank=True, help_text='Warranty duration in months', null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.assetbrand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.assetcategory')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_fixedasset_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_cpu_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('gpu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_gpu', to='asset_management.fixedasset')),
                ('hdd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_hdd', to='asset_management.fixedasset')),
                ('processor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_processor', to='asset_management.fixedasset')),
                ('ram1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ram1', to='asset_management.fixedasset')),
                ('ram2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ram2', to='asset_management.fixedasset')),
                ('ssd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ssd', to='asset_management.fixedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
