# Generated by Django 3.2.8 on 2025-09-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0036_assetbrand_assetcategory_cpu_fixedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='gpu',
            field=models.OneToOneField(blank=True, limit_choices_to={'category__name': 'GPU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_gpu', to='asset_management.fixedasset'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='hdd',
            field=models.OneToOneField(blank=True, limit_choices_to={'category__name': 'HDD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_hdd', to='asset_management.fixedasset'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='processor',
            field=models.OneToOneField(limit_choices_to={'category__name': 'Processor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_processor', to='asset_management.fixedasset'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ram1',
            field=models.OneToOneField(limit_choices_to={'category__name': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ram1', to='asset_management.fixedasset'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ram2',
            field=models.OneToOneField(limit_choices_to={'category__name': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ram2', to='asset_management.fixedasset'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ssd',
            field=models.OneToOneField(limit_choices_to={'category__name': 'SSD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ssd', to='asset_management.fixedasset'),
        ),
    ]
