# Generated by Django 3.2.8 on 2025-09-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0037_auto_20250917_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='ram2',
            field=models.OneToOneField(blank=True, limit_choices_to={'category__name': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_ram2', to='asset_management.fixedasset'),
        ),
    ]
