# Generated by Django 3.2.8 on 2025-09-17 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0338_alter_employeesocial_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0038_alter_cpu_ram2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chair', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Chair'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_chair', to='asset_management.fixedasset')),
                ('cpu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_cpu', to='asset_management.cpu')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_employeefixedasset_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_fixed_assets_employee', to='employee.employee')),
                ('headphone', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Headphone'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_headphone', to='asset_management.fixedasset')),
                ('keyboard', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Keyboard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_keyboard', to='asset_management.fixedasset')),
                ('monitor1', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Monitor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_monitor1', to='asset_management.fixedasset')),
                ('monitor2', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Monitor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_monitor2', to='asset_management.fixedasset')),
                ('mouse', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Mouse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_mouse', to='asset_management.fixedasset')),
                ('table', models.OneToOneField(blank=True, limit_choices_to={'category__name': 'Table'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_fixed_asset_table', to='asset_management.fixedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
