# Generated by Django 3.2.8 on 2025-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0039_employeefixedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='serial',
            field=models.CharField(default=None, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='serial',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
