# Generated by Django 3.2.8 on 2025-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0040_auto_20250917_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='serial_short_form_prefix',
            field=models.CharField(blank=True, help_text='KB, MS, HP, RM, SSD, HDD, GPU', max_length=50, null=True),
        ),
    ]
