# Generated by Django 3.2.8 on 2025-09-17 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0041_assetcategory_serial_short_form_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='ram',
        ),
        migrations.AddField(
            model_name='cpu',
            name='asset_id',
            field=models.CharField(default=None, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='asset_id',
            field=models.CharField(default=None, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RAMSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ram_capacity', models.CharField(help_text='RAM capacity in GB.', max_length=10, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_ramsize_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_size', models.CharField(help_text='Screen size in inches e.g., 24', max_length=10, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_monitorsize_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='ram_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.ramsize'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='display_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.monitorsize'),
        ),
    ]
