# Generated by Django 3.2.8 on 2025-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0042_auto_20250917_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefixedasset',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
