# Generated by Django 3.2.8 on 2025-09-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0043_employeefixedasset_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='storage',
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='processor',
            field=models.CharField(blank=True, help_text='Processor details', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SSDorHDDSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_capacity', models.CharField(help_text='RAM capacity in GB.', max_length=10, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_ssdorhddsize_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='storage_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_storage', to='asset_management.ssdorhddsize'),
        ),
    ]
