# Generated by Django 3.2.8 on 2025-09-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0044_auto_20250924_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='processor',
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='storage_size',
            field=models.ForeignKey(blank=True, help_text='Storage size in GB.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_storage', to='asset_management.ssdorhddsize'),
        ),
        migrations.AlterField(
            model_name='ssdorhddsize',
            name='storage_capacity',
            field=models.CharField(help_text='SSD or HDD capacity in GB. exm: 32', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ProcessorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor_info', models.CharField(help_text='for Intel: i5-10th or i7-13th', max_length=255, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_processordata_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processors',
            },
        ),
        migrations.CreateModel(
            name='CasingBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Brand name', max_length=255, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_casingbrand_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='core',
            field=models.ForeignKey(blank=True, help_text='Processor details: i5-13th', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_core', to='asset_management.processordata'),
        ),
    ]
