# Generated by Django 3.2.8 on 2025-09-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0045_auto_20250924_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='serial',
        ),
        migrations.AddField(
            model_name='cpu',
            name='casing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_casings', to='asset_management.casingbrand'),
        ),
        migrations.AlterField(
            model_name='casingbrand',
            name='name',
            field=models.CharField(help_text='Brand name, HP, DELL, etc.', max_length=255, unique=True),
        ),
    ]
