# Generated by Django 3.2.8 on 2025-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0046_auto_20250924_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefixedasset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
