# Generated by Django 3.2.8 on 2025-09-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0345_employeetaxacknowledgement'),
        ('asset_management', '0047_employeefixedasset_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGN', 'Assign'), ('RETURN', 'Return')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management.fixedasset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
