# Generated by Django 3.2.8 on 2025-09-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0048_assetassignmentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefixedasset',
            options={'permissions': [('cal_view_all_employee_asset', 'Can view all employee fixed asset')]},
        ),
    ]
