# Generated by Django 3.2.8 on 2025-09-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0049_alter_employeefixedasset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignmentlog',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.cpu'),
        ),
        migrations.AlterField(
            model_name='assetassignmentlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.fixedasset'),
        ),
    ]
