# Generated by Django 3.2.8 on 2025-10-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0050_auto_20250929_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='monitor1',
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='monitor2',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='monitor',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Monitor'}, related_name='employee_fixed_asset_monitor1', to='asset_management.FixedAsset'),
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='web_cam',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Webcam'}, related_name='employee_fixed_asset_webcam', to='asset_management.FixedAsset', verbose_name='Web Cam'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='chair',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='chair',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Chair'}, related_name='employee_fixed_asset_chair', to='asset_management.FixedAsset'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='cpu',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='cpu',
            field=models.ManyToManyField(related_name='employee_fixed_asset_cpu', to='asset_management.CPU'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='headphone',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='headphone',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Headphone'}, related_name='employee_fixed_asset_headphone', to='asset_management.FixedAsset'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='keyboard',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='keyboard',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Keyboard'}, related_name='employee_fixed_asset_keyboard', to='asset_management.FixedAsset'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='mouse',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='mouse',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Mouse'}, related_name='employee_fixed_asset_mouse', to='asset_management.FixedAsset'),
        ),
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='table',
        ),
        migrations.AddField(
            model_name='employeefixedasset',
            name='table',
            field=models.ManyToManyField(limit_choices_to={'category__name': 'Table'}, related_name='employee_fixed_asset_table', to='asset_management.FixedAsset'),
        ),
        migrations.CreateModel(
            name='HeadPhoneFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(help_text='Headphone feature', max_length=255, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_management_headphonefeature_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='headphone_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='asset_management.headphonefeature', verbose_name='Feature'),
        ),
    ]
