# Generated by Django 3.2.8 on 2025-10-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0346_alter_employeerating_month'),
        ('asset_management', '0051_auto_20251007_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(db_index=True, help_text='Table, Chair, Monitor, Keyboard, Mouse, Headphone, RAM, SSD, HDD, GPU, Webcam', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='chair',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Chair'}, related_name='employee_fixed_asset_chair', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='cpu',
            field=models.ManyToManyField(blank=True, related_name='employee_fixed_asset_cpu', to='asset_management.CPU'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_fixed_assets_employee', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='headphone',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Headphone'}, related_name='employee_fixed_asset_headphone', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='keyboard',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Keyboard'}, related_name='employee_fixed_asset_keyboard', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='monitor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Monitor'}, related_name='employee_fixed_asset_monitor1', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='mouse',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Mouse'}, related_name='employee_fixed_asset_mouse', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='table',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Table'}, related_name='employee_fixed_asset_table', to='asset_management.FixedAsset'),
        ),
        migrations.AlterField(
            model_name='employeefixedasset',
            name='web_cam',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Webcam'}, related_name='employee_fixed_asset_webcam', to='asset_management.FixedAsset', verbose_name='Web Cam'),
        ),
    ]
