# Generated by Django 3.2.8 on 2025-10-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0052_auto_20251007_1322'),
        ('asset_management', '0052_auto_20251007_1652'),
    ]

    operations = [
    ]
