# Generated by Django 3.2.8 on 2025-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0053_merge_0052_auto_20251007_1322_0052_auto_20251007_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the asset', max_length=100, null=True, unique=True),
        ),
    ]
