# Generated by Django 3.2.8 on 2025-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0054_alter_fixedasset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the asset', max_length=100, null=True),
        ),
    ]
