# Generated by Django 3.2.8 on 2025-10-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0353_merge_20251017_1304'),
        ('asset_management', '0055_alter_fixedasset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefixedasset',
            name='employee',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
