# Generated by Django 3.2.8 on 2025-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0056_alter_employeefixedasset_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefixedasset',
            name='extra',
        ),
    ]
