# Generated by Django 3.2.8 on 2025-11-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0057_remove_employeefixedasset_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefixedasset',
            name='extra',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name__icontains': 'Extra'}, related_name='employee_fixed_asset_extra', to='asset_management.FixedAsset'),
        ),
    ]
