# Generated by Django 3.2.8 on 2025-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0058_employeefixedasset_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'verbose_name': 'Request/Issues', 'verbose_name_plural': 'Request/Issues'},
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15),
        ),
    ]
