# Generated by Django 3.2.8 on 2025-12-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0059_auto_20251202_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'permissions': [('can_view_all_request', 'Can view all request')], 'verbose_name': 'Request/Issues', 'verbose_name_plural': 'Request/Issues'},
        ),
    ]
